### ISSUE TITLE
Please create tag(s)

### ISSUE THREAD

**Issue by ilovezfs** [libtom/libtomcrypt#110]
Do you mind creating a new tag so Homebrew can get the fixes that let it run on El Capitan? Just need a new tag created here on GitHub.

**Comment by sjaeckel** [comment]
You can bring yourself in if you have the time :-)

https://github.com/libtom/libtomcrypt/milestones/v2.0.0

PR's are always welcome

**Comment by karel-m** [comment]
I suggest closing this one. Once there is at least a RC then we can create a tag.
