### ISSUE TITLE
Build failed on Windows

### ISSUE THREAD

**Issue by ricardovsilva** [libtom/libtomcrypt#112]
I'm trying to build using Visual Studio and I'm getting the following error:

> Cannot open include file: 'tommath.h': No such file or directory.

This error is happening on ltm_desc.c file.

**Comment by zero334** [comment]
Build libtommath from https://github.com/libtom/libtommath into a lib and link against it.

**Comment by karel-m** [comment]
I suggest closing this one.

**Comment by karel-m** [comment]
The latest MSVC improvements are in #168 please move future discussion (if any) there.
