### ISSUE TITLE
rsa_encrypt_key function on RSA keys of size 3072 and higher

### ISSUE THREAD

**Issue by JohnMikeS** [libtom/libtomcrypt#117]
Let me preface this with the fact that I've pulled my hair out for the past 3 days trying to find a solution for this.

The problem I face is that the the rsa_encrypt_key function returns CRYPT_ERROR half the time when using RSA keys of size (3072 / 8) or (4096 / 8). I have literally ripped the example code from the manual, changed the buffer sizes of pt2 and out to 4096 * 8, changed the key to (4096 / 8, 65537), and it still gives me this seemingly 50/50 chance to return CRYPT_OK.

I have even tried this on a statically generated random number, and looped the rsa_encrypt_key function on it at the rate of 5 times per second, and the result is still roughly 50/50, either 0 or 1. I am literally baffled by this. I suspect this is the result of pkcs_1_oaep_encode, which is called internally from rsa_encrypt_key, as when I simply use rsa_exptmod on a static random number, it gives a consistent result of 0.

What is strange is that all is good and well when the RSA key used is of size 2048 or lower, as was shown in the manual's example. However, the description for rsa_make_key clearly states that it should work for keys up to 512 bytes long, yet this does not seem to be the case.

**Comment by tomstdenis** [comment]
What math provider are you using?  If you're using TFM then the default
(FP_MAX_SIZE) is to handle numbers upto 2048-bits long by default.  You
need to increase that and recompile TFM first and then rebuild your app.

LTM should handle 4096-bit numbers out of the gate but TFM is a fixed
precision library.

There's nothing in the PKCS #1 code specific to any sizes.  It computes the
buffer sizes on the fly from the length of rsa_key.N rounded up to the next
byte.

Tom

**Comment by JohnMikeS** [comment]
I was, in fact, using TFM out the box. Thanks for the pointers and cheers, Tom. I'll let you know if there are still any issues.
