### ISSUE TITLE
128-bit AES CTR mode - decryptes only first block

### ISSUE THREAD

**Issue by peterfeifanchen** [libtom/libtomcrypt#118]
I am using OPTEE_OS TEE Internal API which uses libtomcrypt below it. I am wondering, what kind of errors could cause only the first block (16 bytes) to be decrypted correctly? 

I am unfamiliar with block ciphers such as AES. So should I be focusing on the 128-bit key (maybe I passed it in wrong? Although in that case, how would I have been able to decrypt even the first 128 bits), IV?

P.S. I used libtomcrypt directly and it worked fine. I must have passed in something wrong to the API that uses libtomcrypt, just wondering if the features of this error is unique enough to narrow it down for me to see what went wrong.

**Comment by pascal-brand-st-dev** [comment]
I could not answer from this.
You can have a look at the test 4003 https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L2304 that tests CTR configuration https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L2228

**Comment by sjaeckel** [comment]
If you already know that it works with plain libtomcrypt why don't you open an issue in the tracker of OP-TEE?
