### ISSUE TITLE
DH small subgroup confinement attack

### ISSUE THREAD

**Issue by ltv511** [libtom/libtomcrypt#119]
In the dh_shared_secret function in https://github.com/libtom/libtomcrypt/blob/develop/src/pk/dh/dh.c, there is no subgroup order validation of the public key. To properly validate subgroup order, for a non-safe prime p and a known subgroup order q, a received Diffie-Hellman key exchange value y should satisfy y^q == 1 mod p. For a safe prime, it suffices to check that y is not 1 or p-1.

All of the built-in libTomCrypt primes are safe primes, but if there is no check that y is not 1 or p-1, an application built using libTomCrypt could be vulnerable to a small subgroup confinement attack.

**Comment by karel-m** [comment]
closed by #225
