### ISSUE TITLE
AES Random Access Decryption Issue

### ISSUE THREAD

**Issue by peterfeifanchen** [libtom/libtomcrypt#120]
I am using 128-bit AES CTR. The IV of 0, big endian, and cipher is aes_desc. I am trying to decrypt non-sequentially (e.g. if I have a file that is 54 bytes long, I want to be able to decrypt from offset 0,16,32, 48). I think theoretically I should only need to modify the symmetric_CTR->ctr's first 32 bytes of the array. For example, if I want to decrypt from offset 16, I add 1 to symmetric_CTR->ctr[15]. 

However the problem is I can decrypt with offset 0, 32, 48 by initializing the ctr to 0, 2, 3 before I start calling ctr_decrypt. But when I set it to 16, I am unable to decrypt the block from byte 16 to 32, but I can decode the rest. When I want to decode starting from byte 32, I can decode every block from byte 32 onwards. What am I doing wrong?

**Comment by peterfeifanchen** [comment]
I think the issue is the symmetric_Ctr->pad does not get updated until the second iteration. It still uses the original pad for offset 0.

**Comment by sjaeckel** [comment]
Can you please create a minimal testcase that shows the issue you're describing!?

**Comment by karel-m** [comment]
I suggest closing this one.

**Comment by sjaeckel** [comment]
@peterfeifanchen feel free to open it again as soon as you can provide us a minimal testcase
