### ISSUE TITLE
ccm_init facelift

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#123]
This issue is related to incremental CCM processing added in #55 by @pascal-brand-st-dev

The main reason for opening this issue is the fact that `ccm_init(..)` requires as a parameter plaintext lenght `ptlen` which in my use case I simply do not know at the point where I am calling `ccm_init`.

I would like to propose reconsidering current CCM API so that it is more close to libtomcrypt's already existing GCM API.

Now we have CCM API like this:

``` c
int ccm_init(ccm_state *ccm, int cipher, const unsigned char *key, int keylen, int ptlen, int taglen, int aad_len);
int ccm_reset(ccm_state *ccm);
int ccm_add_nonce(ccm_state *ccm, const unsigned char *nonce, unsigned long noncelen);
int ccm_add_aad(ccm_state *ccm, const unsigned char *adata, unsigned long adatalen);
int ccm_process(ccm_state *ccm, unsigned char *pt, unsigned long ptlen, unsigned char *ct, int direction);
int ccm_done(ccm_state *ccm, unsigned char *tag, unsigned long *taglen);
```

And GCM API like this:

``` c
int gcm_init(gcm_state *gcm, int cipher, const unsigned char *key, int keylen);
int gcm_reset(gcm_state *gcm);
int gcm_add_iv(gcm_state *gcm, const unsigned char *IV, unsigned long IVlen);
int gcm_add_aad(gcm_state *gcm, const unsigned char *adata, unsigned long adatalen);
int gcm_process(gcm_state *gcm, unsigned char *pt, unsigned long ptlen, unsigned char *ct, int direction);
int gcm_done(gcm_state *gcm, unsigned char *tag, unsigned long *taglen);
```

So my suggestion is changing `ccm_init` like this

``` c
int ccm_init(ccm_state *ccm, int cipher, const unsigned char *key, int keylen);
```

Just for curiosity here is how OpenSSL handles CCM/GCM
https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption#Authenticated_Encryption_using_CCM_mode

**Comment by sjaeckel** [comment]
> Just for curiosity here is how OpenSSL handles CCM/GCM

That looks like their API is very similar to our CCM API!?!

...and looking at the CCM algorithm/implementation I can't see a way to realize the suggested API...

**Comment by karel-m** [comment]
You are right, but we can have at least:
```
int ccm_init(ccm_state *ccm, int cipher, const unsigned char *key, int keylen, int taglen);
```

I need to get rid of `ptlen` in `ccm_init`

**Comment by karel-m** [comment]
I was wrong `ptlen` cannot be avoided in `ccm_init`, closing.
