### ISSUE TITLE
ECDSA sign/verify failed 50 out of 10000 when use libtomcrypt

### ISSUE THREAD

**Issue by z7z8th** [libtom/libtomcrypt#126]
When doing ECDSA sign/verify test:
I generated 100 private & public key pairs, and 100 hash values.
Then sign 100 times with the same private & public key pair and hash value, to generate 100 signatures.
Totally 10000 signatures is generated.
Then verify the signature with the corresponding public key and hash value, 50 times out of 10000 verification will fail.

Can you help confirm if libtomcrypt problem?

the ECC curve is y^2 = x^3 - 3x + b, ECC length 384bits,
the math lib is gmp on cygwin.
If you need the test code, I can upload it.

The curve parameters is as follow:
{
size: 48,
name: "ECC-384",
prime: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFF0000000000000000FFFFFFFF",
B: "B3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF",
order of the curve: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973",
Gx: "AA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7",
Gy: "3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F",
},

**Comment by z7z8th** [comment]
Hi,

I've uploaded the code to github.

https://github.com/z7z8th/libtomcrypt-develop-20160729
https://github.com/z7z8th/ecc_tools

build and test steps(on cywin or linux):
```
cd libtomcrypt-develop-20160729
bash ./build-env
cd ../ecc_tools
make
./test.sh
```
then, you'll see some verify failed.

Thanks
Bob

**Comment by karel-m** [comment]
Hi Bob,

could you please try your test with branch miko-ecc-enhancements ?

Regards, Karel

**Comment by z7z8th** [comment]
HI, Karel,

I tried miko-ecc-enhancements, verify still fails.

Regards
Bob

**Comment by sjaeckel** [comment]
... and it's not gmp dependant, also ltm fails

**Comment by z7z8th** [comment]
Hi, 

I found the cause, it's not tomcrypt problem.
I didn't use the mp_to_unsigned_bin right, after export to unsigned bin in wrong way, I can't import it correctly.
Previous wrong usage:
mp_to_unsigned_bin(key->pubkey.x, pub[0])
Should be:
mp_to_unsigned_bin(key->pubkey.x, pub[0]+ECC_KEY_SIZE-mp_unsigned_bin_size(key->pubkey.x))

Thanks a lot for your help anyway.
