### ISSUE TITLE
Doc unclear about the difference between XXX_setup and XXX_start

### ISSUE THREAD

**Issue by matswebjorn** [libtom/libtomcrypt#128]
"3.1.1 Key Scheduling" states that "All ciphers must provide six visible functions which are (given that XXX is the name of the cipher) the following: 
int XXX_setup(const unsigned char *key, int keylen,int rounds, symmetric_key *skey)"

But there is no cbc_setup(). 

Instead "3.4.4 Initialization" describes a 
int XXX_start(int cipher, const unsigned char *IV, const unsigned char *key, int keylen,int num_rounds, symmetric_XXX *XXX) which calls descriptor method setup. So it seems to do the same thing as XXX_setup is supposed to do. But it is unclear. particulary the difference in names makes it confusing.

**Comment by sjaeckel** [comment]
3.1 deals with ciphers, 3.4 deals with modes.

It's true they could be called the same but tom chose to call them like that and I'd say we stick with it. 
You're gonna get used to it ;-)

Probably he also had a particular reason to call them differently?! /cc @tomstdenis
