### ISSUE TITLE
VS custom build step for aes.c fails due to spaces in source path

### ISSUE THREAD

**Issue by grimdoomer** [libtom/libtomcrypt#131]
On a windows computer compiling with Visual Studio the custom build step for aes.c will fail if your folder path contains spaces. This is due to the missing quotes around the %(FullPath) macro. 

It would also be a good idea to use the %(PreprocessorDefinitions) macro instead of manually putting the preprocessor macros on the command line. This makes it transparent if you have to enable LTC_NO_FAST like I did.

Here is the updated command line for both the fix for the first issue, and the recommendation for the second:

`cl /nologo /MLd /W3 /Gm /GX /ZI /Od /I "src\headers" /I "..\libtommath" %(PreprocessorDefinitions) /Fp"Debug/libtomcrypt.pch" /YX /Fo"Debug/" /Fd"Debug/" /FD /GZ /c "%(FullPath)"
cl /nologo /DENCRYPT_ONLY /MLd /W3 /Gm /GX /ZI /Od /I "src\headers" /I "..\libtommath" %(PreprocessorDefinitions)  /Fp"Debug/libtomcrypt.pch" /YX /Fo"Debug/aes_enc.obj" /Fd"Debug/" /FD /GZ /c "%(FullPath)"`

**Comment by sjaeckel** [comment]
Would you mind creating a patch of the involved files or even open a PR?

**Comment by grimdoomer** [comment]
Sure thing.

**Comment by karel-m** [comment]
@grimdoomer ping

**Comment by karel-m** [comment]
Just for record: as far as I can see there is not a single occurrence of the string `FullPath` in the whole libtomcrypt

**Comment by grimdoomer** [comment]
FullPath is a VS macro relating to the opened project. In this case FullPath is the path of aes.c. I'm creating a pull request momentarily.

**Comment by grimdoomer** [comment]
I submitted a pull request #165

**Comment by karel-m** [comment]
Let us move the discussion to #165

Closing this one.
