### ISSUE TITLE
Is possible use my own parameter to set RSA key

### ISSUE THREAD

**Issue by rangewang** [libtom/libtomcrypt#136]
Is possible to set the RSA public key detail with my own parameter, like the modulus "N"
and set the RSA private key detail with my own parameter, like the d, p, q, etc.

the parameters are define in this struct

/** RSA LTC_PKCS style key */
typedef struct Rsa_key {
/** Type of key, PK_PRIVATE or PK_PUBLIC */
int type;
/** The public exponent */
void *e; 
/** The private exponent */
void *d; 
/** The modulus */
void *N; 
/** The p factor of N */
void *p; 
/** The q factor of N */
void *q; 
/** The 1/q mod p CRT param */
void *qP; 
/** The d mod (p - 1) CRT param */
void *dP; 
/** The d mod (q - 1) CRT param */
void *dQ;
} rsa_key;

**Comment by sjaeckel** [comment]
`rsa_import()`?

**Comment by karel-m** [comment]
Or as I have proposed in #97 (it assumes that you have all numbers - e, d, N, p ... - as hexadecimal strings):

```c
int rsa_import_hex(char *N, char *e, char *d, char *p, char *q,
                            char *dP, char *dQ, char *qP, rsa_key *key)
{
   int err;

   LTC_ARGCHK(key         != NULL);
   LTC_ARGCHK(N           != NULL);
   LTC_ARGCHK(e           != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);

   err = mp_init_multi(&key->e, &key->d, &key->N, &key->dQ, 
                                &key->dP, &key->qP, &key->p, &key->q, NULL);
   if (err != CRYPT_OK) return err;

   if ((err = mp_read_radix(key->N , N , 16)) != CRYPT_OK)   { goto LBL_ERR; }
   if ((err = mp_read_radix(key->e , e , 16)) != CRYPT_OK)   { goto LBL_ERR; }
   if (d && p && q && dP && dQ && qP && strlen(d)>0 && strlen(p)>0 && 
       strlen(q)>0 && strlen(dP)>0 && strlen(dQ)>0 && strlen(qP)>0) {
     if ((err = mp_read_radix(key->d , d , 16)) != CRYPT_OK) { goto LBL_ERR; }
     if ((err = mp_read_radix(key->p , p , 16)) != CRYPT_OK) { goto LBL_ERR; }
     if ((err = mp_read_radix(key->q , q , 16)) != CRYPT_OK) { goto LBL_ERR; }
     if ((err = mp_read_radix(key->dP, dP, 16)) != CRYPT_OK) { goto LBL_ERR; }
     if ((err = mp_read_radix(key->dQ, dQ, 16)) != CRYPT_OK) { goto LBL_ERR; }
     if ((err = mp_read_radix(key->qP, qP, 16)) != CRYPT_OK) { goto LBL_ERR; }
     key->type = PK_PRIVATE;
   }
   else {
     key->type = PK_PUBLIC;
   }
   return CRYPT_OK;

LBL_ERR:
   mp_clear_multi(key->d, key->e, key->N, key->dQ, key->dP, key->qP, key->p, key->q, NULL);
   return err;
}
```

**Comment by rangewang** [comment]
Thanks karel-m

I set my won numbers with hexadecimal strings, and doing well now.

This rsa_import_hex is useful.

**Comment by rangewang** [comment]
Thanks karel-m

I set my won numbers with hexadecimal strings, and doing well now.

This rsa_import_hex is useful.
