### ISSUE TITLE
Libtom.(org|net) - This Domain Name Has Expired

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#138]
Currently both sites http://www.libtom.org/ + http://www.libtom.net/ just show a message about domain expiration.

**Comment by sjaeckel** [comment]
.net doesn't for me, it shows as just empty... it's registered on me and I've renewed lately.

... and it should still forward to libtom.github.io as of the settings page of the registrar ...

.org shows a placeholder, true.  

Now let's hope tom still has registered .org ...

**Comment by sjaeckel** [comment]
Apparently libtom.net forwards to libtom.github.io which forwards to libtom.org which is broken...

**Comment by sjaeckel** [comment]
Ping @tomstdenis

**Comment by sjaeckel** [comment]
I guess an easy fix at least for libtom.net could be to modify the CNAME file at let it point to www.libtom.net!?

Could someone please try it out? @sebastianas probably?

**Comment by sebastianas** [comment]
Updated the CNAME entry for the homepage.

**Comment by ray-pixar** [comment]
http://www.libtom.net/ shows an empty page.

**Comment by sjaeckel** [comment]
libtom.net works again.

Let's see what happens with .org ...

**Comment by ray-pixar** [comment]
look at this page:
http://www.namejet.com/Pages/Auctions/BackorderDetails.aspx?domainname=libtom.org
libtom.net will expire in 13 days and you can buy it again.

**Comment by rofl0r** [comment]
the libtom.net startpage has a matrix with published releases, however missing a crucial thing: the release date.

**Comment by karel-m** [comment]
Does any of you managed to register/takeover libtom.org? Or is it now owned by somebody completely outside of any libtom related projects?

https://who.is/whois/libtom.org

**Comment by sjaeckel** [comment]
I tried to register it via the auction but without success.

After that I had several e-mails in my inbox from a ~~blackmailer~~ company called dott.net who's now the owner of the domain. They asked me if I want to buy the domain, I asked them to quote me a price and never heard back from them ... (I also sent a reminder, but still nothing) ... I guess that domain's gone ...

**Comment by karel-m** [comment]
Ok, in that case we should perhaps replace all occurrences of libtom.org in
source codes with libtom.net (or libtom's pages on github).

**Comment by sebastianas** [comment]
On 2017-02-21 07:51:58 [-0800], karel-m wrote:
> Does any of you managed to register/takeover libtom.org? Or is it now owned by somebody completely outside of any libtom related projects?

I don't. And based on whois and current content I doubt that it is
someone from the project.

Sebastian

**Comment by karel-m** [comment]
IMO not much to do here, closing.
