### ISSUE TITLE
SAFER+ reversed byte order

### ISSUE THREAD

**Issue by sylvainpelissier** [libtom/libtomcrypt#140]
It seems that the SAFER+ implementation in libtomcrypt use the reverse byte order compared to the test vectors given here:

https://web.archive.org/web/20060629134642/http://csrc.nist.gov/CryptoToolkit/aes/round1/testvals/saferpls-vals.zip

 This issue was also mentioned here:

http://www.users.zetnet.co.uk/hopwood/crypto/scan/cs.html#SAFER+

For example the NIST test vector gives:

    KEYSIZE=128

    PT=45d77c9a652c7eaaaf3b87bcfd794825
    KEY=78ae8da840f61247136ec75a68a71cae

    Round[1]=c9c3e735d7725b84b40aec2a769c0fca
    Round[2]=d011250d23a0e86e227a4a894c18f091
    Round[3]=a8096a0496e34d526db178a418f7f482
    Round[4]=820930e60a8e3a3b6b0bd5cf746528e7
    Round[5]=b1538dab31c7dcf43d6be80fe0f09351
    Round[6]=6950823c4070720120a150d5ef42f738
    Round[7]=4381fdf9afe3db99bdf40b0fa02f1f05
    Round[8]=388e5d6b3c64c75299b494cb9f933299

And with libtomcrypt I obtained:

    PT=254879fdbc873bafaa7e2c659a7cd745
    KEY=ae1ca7685ac76e134712f640a88dae78
    CT=9932939fcb94b49952c7643c6b5d8e38

**Comment by sjaeckel** [comment]
hmm, I guess the best way will be to fix this and hope that nobody uses the code and updates blindly :)

**Comment by sylvainpelissier** [comment]
Hi,

After a further research, I found that Bluetooth uses the same byte ordering as now in libtomcrypt. For example: https://github.com/mikeryan/btcrack/blob/master/btcrack.c gives the same output. I think the current implementation matches the test vectors given in the reference paper (https://github.com/stamparm/cryptospecs/raw/master/symmetrical/specs/safer+.pdf) so maybe we should keep it as it is.

**Comment by karel-m** [comment]
Great! Thanks for your time spent on researching this issue.

Closing.
