### ISSUE TITLE
Polish dsa_* interface

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#154]
As discussed in #148 the interface of the following DSA related functions is worth some discussion:
```
int dsa_make_key_ex(prng_state *prng, int wprng, int group_size, int modulus_size, dsa_key *key, char* p_hex, char* q_hex, char* g_hex);
int dsa_make_params(prng_state *prng, int wprng, int group_size, int modulus_size, void *p, void *q, void *g);
```

**Comment by buggywhip** [comment]
> On Feb 28, 2017, at 11:37 AM, karel-m <notifications@github.com> wrote:
> As discussed in #148 the interface of the following DSA related functions is worth some discussion:
> 
> int dsa_make_key_ex(prng_state *prng, int wprng, int group_size, int modulus_size, dsa_key *key,
> char* p_hex, char* q_hex, char* g_hex);
> int dsa_make_params(prng_state *prng, int wprng, int group_size, int modulus_size, void *p, void *q, void *g);

You are right, DSA needs some attention.

First, use of DSA based on 1024-bit keys and 160-bit SHA-1 should be discouraged.  NIST FIPS 186-4 describes versions of DSA that support 2048- and 3084-bit key lengths and stronger hash algorithms.  A quick review of the current LTC algorithms suggests they do not support parameter and key generation as specified by 186-4.
    http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf (current version)
    http://csrc.nist.gov/publications/fips/fips186-3/fips_186-3.pdf (retired/archived)

----------------

From the "[libtom/libtomcrypt] use static functions where appropriate (#148)" thread...
> On Feb 28, 2017, at 9:34 AM, Steffen Jaeckel <notifications@github.com> wrote:
> why someone would want to use dsa_make_params() itself!?

Second, IIRC, and assuming I understand your question...

DSA is based on the difficulty of computing discrete logarithms.  The public-private key generation process uses parameters p, q, and g when generating keys, but those parameters need not be kept secret nor do they have to be unique.  They simply have to be strong primes.  ...and better yet, safe primes.  

Calculating good, large primes takes a lot of computing horsepower, and years ago that also meant very long wait times.  Thus, parameter sets were pre-calculated, distributed, and frequently reused.  This dramatically shorted public-private key generation times.  Even today, the effort required to find suitable primes is non-trivial, especially when looking for longer primes, making a separate dsa_make_params() function desirable.  

...or were you asking a different question?

----------------

Third, the API for dsa_make_key_ex() should easily accomodate the param output fm dsa_make_params().  But what should be the standard/convention for storing and passing the parameters p, q, g?  Individual binaries?  Not recommended.  A struct of binaries?  Better.  What about hex?  I dunno; I have not thought this thru.  But whatever, consideration should also be given to the form parameters are likely to be received fm outside sources.  My guess that will likely be some form of hex.  ???



.

**Comment by buggywhip** [comment]
> On Feb 28, 2017, at 9:09 PM, Larry Bugbee <bugbee@mac.com> wrote:
> 
> A quick review of the current LTC algorithms suggests they do not support parameter and key generation as specified by 186-4.
>    http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf (current version)
>    http://csrc.nist.gov/publications/fips/fips186-3/fips_186-3.pdf (retired/archived)

My apologies.  Please disregard the above as I was looking at some old code.  I checked the develop branch and it looks a lot like 186-4.  Mea Culpa.

**Comment by karel-m** [comment]
> But what should be the standard/convention for storing and passing the parameters p, q, g?

This is exactly the question to be answered.  And it should be preferably to some extent consistent across the whole library (dsa, ecc, rsa, dh).

There is no hurry to decide this right know as aligning the code to the chosen solution will not be that complicated.

**Comment by buggywhip** [comment]
> On Mar 1, 2017, at 3:34 PM, karel-m <notifications@github.com> wrote:
> But what should be the standard/convention for storing and passing the parameters p, q, g?
> 
> This is exactly the question to be answered. And it should be preferably to some extent consistent across the whole library (dsa, ecc, rsa, dh).
> 
And I agree.  My primary concern is being sure we "bundle" p, q, g because those values are a set.  Dumb, but doing a mix-n-match with values fm another param set would not be pretty.  

I am less concerned about the exact format of the struct other than it should not have pointers.  Its structure should be flat, and because I usually come at LibTom fm Python, I and other dynamic language users would need to know (or be able to easily determine) the size of the struct.  (see src/misc/crypt/crypt_sizes.c)  

...and if params come (or are to be sent) by PEM blocks or such, conversion utilities would be nice-to-have, a very low priority.

And my concerns are just that, concerns, not problems.  

I do appreciate you throwing this up for discussion.  Thanks. 👍

**Comment by karel-m** [comment]
My suggestion:
* keep `dsa_make_key_ex` as it is (= p, q, g passed as hexadecimal strings)
* remove `dsa_make_params` from public API (it was not part of API in 1.17 therefore it does not break backwards compatibility)
* see 7d0418c82d761 in pr/fix-154-dsa-api

**Comment by karel-m** [comment]
PR #224 merged, closing
