### ISSUE TITLE
x and y params in ROL64, ROL64c, ROR64, ROR64c macros expected to be 64-bit in size but document crypt.pdf page 9 says unsigned long type.

### ISSUE THREAD

**Issue by ghost** [libtom/libtomcrypt#16]
x and y params in ROL64, ROL64c, ROR64, ROR64c macros expected to be 64-bit in size but document crypt.pdf page 9 says unsigned long type. The document should be updated to say 64-bit size params for these 64-bit macros.

Changes required in doc/crypt.pdf page 9.

**Comment by karel-m** [comment]
I propose closing this one as it is fixed in feature/doc (#54)
