### ISSUE TITLE
API/ABI changes review for LibTomCrypt

### ISSUE THREAD

**Issue by lvc** [libtom/libtomcrypt#170]
The review of API/ABI changes for LibTomCrypt since 1.07 version: https://abi-laboratory.pro/tracker/timeline/libtomcrypt/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![libtomcrypt-1](https://cloud.githubusercontent.com/assets/1517837/24091053/0c563dce-0d5f-11e7-8cb2-b592e5bd4403.png)

![libtomcrypt-2](https://cloud.githubusercontent.com/assets/1517837/24091058/14520a4e-0d5f-11e7-9222-5492f6ee2d22.png)

**Comment by sjaeckel** [comment]
Cool, that looks very neat.

Is there a possibility to have the results of 'last version' vs 'next version'? for ltc that'd be tag 1.17 vs develop branch!? I did this lately by hand, but it'd be nice to have them integrated on your page...

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libtomcrypt/

Thank you.

![libtomcrypt-3](https://cloud.githubusercontent.com/assets/1517837/24142387/d7f5d404-0e3f-11e7-8730-f377ce663620.png)

**Comment by sjaeckel** [comment]
Is there some kind of badge that we can include in the README?
If not I'll just add a link to your page.

**Comment by lvc** [comment]
May be this one?

ABI analysis:
<a href='https://abi-laboratory.pro/tracker/timeline/libtomcrypt/'><img src="https://abi-laboratory.pro/tracker/graph/libtomcrypt/graph.png" width="250"/></a>

**Comment by sjaeckel** [comment]
I thought more of nice version of this one ;-)
![badge](https://user-images.githubusercontent.com/294374/27188051-404f1948-51ed-11e7-827f-8222fa5c5b54.png)

**Comment by sjaeckel** [comment]
You know what else would be cool... a tool that tells what the correct libtool version would be. c.f. #300

**Comment by sjaeckel** [comment]
@lvc I just saw that the latest update for the develop branch was "2018-07-03 22:45". Could you please have a look?

**Comment by lvc** [comment]
@sjaeckel 

> @lvc I just saw that the latest update for the develop branch was "2018-07-03 22:45". Could you please have a look?

Thank you for pointing to the problem (broken uploader of reports). It's fixed for now.

See https://abi-laboratory.pro/?view=timeline&l=libtomcrypt

![libtomcrypt-4](https://user-images.githubusercontent.com/1517837/46690756-cf559880-cc0b-11e8-8db2-ca5e35a139f7.png)
