### ISSUE TITLE
Polish error codes

### ISSUE THREAD

**Issue by sjaeckel** [libtom/libtomcrypt#180]
This is a list of the error codes that are defined but not used

```
...
   CRYPT_INVALID_PRNG,     /* Invalid PRNG specified */
...
   CRYPT_PK_INVALID_SYSTEM,/* Invalid PK system specified */
   CRYPT_PK_DUP,           /* Duplicate key already in key ring */
   CRYPT_PK_NOT_FOUND,     /* Key not found in keyring */
...
```

what do you guys think if we just re-use these spots in the enum for new error codes?

**Comment by karel-m** [comment]
* Ad `CRYPT_INVALID_PRNG` - this one we should rather properly use than drop
* The rest should be IMO removed and I think we can reuse related enum spots

**Comment by sjaeckel** [comment]
uhm I just realized that my installed version of `ag` didn't find all occurences of `CRYPT_INVALID_PRNG` and that it's used in the appropriate places...
