### ISSUE TITLE
Significance of  "Number of rounds" in cbc_start method in AES CBC Encryption

### ISSUE THREAD

**Issue by sivarajendranaidu** [libtom/libtomcrypt#192]
I had installed libtomcrypt-devel-1.17-21.el6.x86_64 in my Centos 6.X box and write samples for CBC and CTR (AES-128)
I am trying to encrypt a Data Byte array using AES -128 CBC with a constant IV and Key as follows:
Content Key : 11 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Constant IV : 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Data To Encrypt : 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

        /**
         * Register the cipher for AES
         */
        siEncStatus = register_cipher( &aes_desc );
        if ( CRYPT_OK != siEncStatus )
        {
            LGM_LOG_VALUE( m_tLogId,
                           LGM_LOG_LEVEL_FATAL,
                           "Register of AES Cipher Failed %s",
                           error_to_string(siEncStatus) );
        }

        /**
         * Setup AES-CTR Encryption Engine using ctr_start method
         * with following parameters
         *  AES Cipher
         *  IV
         *  Key
         *  Key_Size
         *  Number of rounds
         *  CBC State
         */
        siEncStatus = cbc_start( find_cipher("aes"),    
                                &ucIV[0],
                                 &ucContentKey[0],
                                 16,
                                 0,//10,//
                                 &m_CbcContext );
        if ( CRYPT_OK != siEncStatus )
        {
            LGM_LOG_VALUE( m_tLogId,
                           LGM_LOG_LEVEL_FATAL,
                           "Setup of AES CBC Cipher Failed with status %s",
                           error_to_string(siEncStatus) );
        }
        for (int i = 0; i < 16; i++ )
            printf("%x ", ucContentKey[i]);
        printf("\n");
        for (int i = 0; i < 16; i++ )
            printf("%x ", ucIV[i]);
        printf("\n");
        for (int i = 0; i < 64; i++ )
            printf("%x ", ucData[i]);
        printf("\n");
        /**
         * Encrypt the AES-CBC Encryption Engine using cbc_encrypt method
         * with following parameters
         *  plaintext
         *  ciphertext
         *  length of plaintext
         *  CBC State Context
         */
        siEncStatus = cbc_encrypt( &ucData[0],
                                   &ucData[0],
                                   64,
                                   &m_CbcContext );
        if ( CRYPT_OK != siEncStatus )
        {
            LGM_LOG_VALUE( m_tLogId,
                           LGM_LOG_LEVEL_FATAL,
                           "Encrypt Data in AES-CBC Cipher Failed with status %s",
                           error_to_string(siEncStatus) );
        }
        for (int i = 0; i < 64; i++ )
            printf("%x ", ucData[i]);
        printf("\n");
        /**
         * Teardown AES-CTR Encryption Engine using ctr_done method
         */
        siEncStatus = cbc_done( &m_CbcContext );
        if ( CRYPT_OK != siEncStatus )
        {
            LGM_LOG_VALUE( m_tLogId,
                           LGM_LOG_LEVEL_FATAL,
                           "Tear down of AES CBC Cipher Failed with status %s",
                           error_to_string(siEncStatus) );
        }

Please provide the significance of "Number of rounds" in cbc_start method.

What should be the value of Number of rounds? is it dependent on the KEY_SIZE?

**Comment by sjaeckel** [comment]
The "Number of rounds" parameter will just be passed to the used symmetric cipher algorithms' setup function.

> What should be the value of Number of rounds? is it dependent on the KEY_SIZE?

"The number of rounds can be set to zero to use the default, which is generally a good idea." c.f. ch. 3.1.1 of the documentation.

Either you choose `0` which will select the number of rounds for you or you pass the correct key size & number of rounds combination which you should be able to determine from the specification of the cipher you want to use (e.g. for AES: key len = 16 (128 bit), # of rounds = 10)
