### ISSUE TITLE
Xcode4, libtomcrypt, LLVM, asm (unknown version of libtomcrypt)

### ISSUE THREAD

**Issue by wolfman2000** [libtom/libtomcrypt#2]
Good _insert time zone here_ everyone. I represent the StepMania 5/StepMania sm-ssc group from [Google Code](http://code.google.com/p/sm-ssc/), and I am trying to work on bringing our project up to date for Xcode 4 on the Mac OS X side. Our project uses libtommath and libtomcrypt. Unfortunately, I do not know what version it is, which makes this issue a little hard to figure out.

The old environment we used, Xcode 3, used GCC 4.0 for historical reasons. With the move to Xcode 4, we wish to take advantage of a faster, better compiler: specifically, LLVM 2.0 (also known as Clang). Unfortunately, that better, faster compiler is not working due to this one small issue.

In `tomcrypt_macros.h`, there are two sets of ROLc and RORc static inline functions that both contain asm code. The core part of one of them is as follows:

``` c
static inline __attribute__((always_inline)) unsigned ROLc(unsigned word, const int i)
{
   asm ("roll %2,%0"
      :"=r" (word)
      :"0" (word),"I" (i));
   return word;
}
```

The compiler complains on aes.c, md5.c, and sha1.c of this message:

`fatal error: error in backend: Invalid operand for inline asm constraint 'I'!`

That function, and three others just like it, are the only occasions where there is the 'I' constraint.

If we try to use GCC 4.2 for libtomcrypt and Clang for the rest of our libraries (including libtommath), this eventually comes up on linking.

```
Ld ../sm-ssc.app/Contents/MacOS/sm-ssc normal i386
    cd /Users/wolfman2000/Repositories/sm-ssc/Xcode
    setenv MACOSX_DEPLOYMENT_TARGET 10.5
    /Developer/usr/bin/clang++ -arch i386 -isysroot /Developer/SDKs/MacOSX10.5.sdk
 -L/Users/wolfman2000/Repositories/sm-ssc/Xcode/..
 -L/Users/wolfman2000/Repositories/sm-ssc/Xcode/build/Debug
 -L/Users/wolfman2000/Repositories/sm-ssc/Xcode/Libraries
 -L/Users/wolfman2000/Repositories/sm-ssc/Xcode/../extern/mad-0.15.1b/msvc++/Release
 -F/Users/wolfman2000/Repositories/sm-ssc/Xcode/..
 -filelist /Users/wolfman2000/Repositories/sm-ssc/Xcode/build/stepmania_xcode4.build/Debug/stepmania.build/Objects-normal/i386/sm-ssc.LinkFileList
 -mmacosx-version-min=10.5 -dead_strip -no_dead_strip_inits_and_terms
 -framework Cocoa -framework Carbon -framework IOKit
 -framework QuickTime -framework OpenGL -framework CoreFoundation
 -framework AudioToolbox -framework AudioUnit -framework CoreAudio
 -framework vecLib -ljpeg_link -logg_link -ltheora_link -lvorbis_link
 -llua-5.1 -ltomcrypt -ltommath -lz_link -lffmpeg_link -lmad-sm5
 -lpng-1.5.1sm0.1 -lglew -lpcre -o /Users/wolfman2000/Repositories/sm-ssc/Xcode/../sm-ssc.app/Contents/MacOS/sm-ssc

ld: illegal text reloc to 
__ZSt7find_ifIN9__gnu_cxx17__normal_iteratorIPN9StdString7CStdStrIcEESt6vectorIS4_SaIS4_EEEEPFbRKS4_EET_SE_SE_T0_St26random_access_iterator_tag from /Users/wolfman2000/Repositories/sm-ssc/Xcode/build/stepmania_xcode4.build
/Debug/stepmania.build/Objects-normal/i386/RageUtil.o in 
__ZSt7find_ifIN9__gnu_cxx17__normal_iteratorIPN9StdString7CStdStrIcEESt6vectorIS4_SaIS4_EEEEPFbRKS4_EET_SE_SE_T0_St26random_access_iterator_tag for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Command /Developer/usr/bin/clang++ failed with exit code 1
```

I admit I am at a loss as to how to properly solve this.

The code we use for libtomcrypt is included in [our repository](http://code.google.com/p/sm-ssc/source/checkout) (Mercurial required). We haven't moved it to our externs yet, so it's located in `src/libtomcrypt/src`. The spcific branch that I am trying to make work is the `XCode4` branch, but I believe any attempts at compiling libtomcrypt via Clang will fail, not just my end. If requested, I will upload just the libtomcrypt part at the location of your choice.

Jason "Wolfman2000" Felds

**Comment by MMI** [comment]
Proposed solution in this [pull request](https://github.com/libtom/libtomcrypt/pull/125)

**Comment by karel-m** [comment]
pull/125 was closed, can we also close this issue?
