### ISSUE TITLE
Shared library is installed without executable bits on Unix

### ISSUE THREAD

**Issue by andreyv** [libtom/libtomcrypt#231]
Steps to reproduce with the `develop` branch:

- Build and install the library using `makefile.shared`.
- Observe that the shared library does not have executable permissions:
`-rw-r--r-- root/root    763856 2017-06-18 14:33 lib/libtomcrypt.so.0.0.117`

**Comment by rofl0r** [comment]
what's the purpose of executable bit on shared objects ?

**Comment by andreyv** [comment]
Mostly it is by convention, but also has practical purposes:

- Some shared libraries are directly executable as programs (not in this case, though).
- `ldd` complains about missing permissions:
  ```
  > ldd libtomcrypt.so
  ldd: warning: you do not have execution permission for `./libtomcrypt.so'
  ```
- Some dynamic loaders (IIRC, macOS loader) may refuse to load non-executable libraries.

**Comment by sjaeckel** [comment]
> what's the purpose of executable bit on shared objects ?

https://unix.stackexchange.com/a/48479 makes somehow sense

**Comment by sjaeckel** [comment]
Fine like that?

**Comment by andreyv** [comment]
This should work. `makefile.shared` could even set this variable to `-m 755` before including the common makefile.

**Comment by sjaeckel** [comment]
I thought the same as @rofl0r until I found the post mentioned above.
As the standard GNU `ldd` doesn't need it I'd prefer to leave it as is and if someone needs the different behavior it can be modified on invocation of `make`.

**Comment by andreyv** [comment]
Fair enough, no problem.
