### ISSUE TITLE
rc1 dsa_set_key API question

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#248]
While switching my perl bindings to the new RC1 API for DH, DSA, RSA I was thinking a bit about `dsa_set_key` API.

In rc1 we have:
```C
int dsa_set_key(const unsigned char *pub, unsigned long publen,
                const unsigned char *priv, unsigned long privlen,
                dsa_key *key);
```
but I think it would be better to have:
```C
int dsa_set_key(const unsigned char *in, unsigned long inlen,
                int type, dsa_key *key);
```

* If you have a public key then you have a public key
* If you have a private key then you have a private key + you can simply calculate the corresponding public key (which we already do in `dsa_set_key`)

**Comment by sjaeckel** [comment]
> If you have a public key then you have a public key
> If you have a private key then you have a private key + you can simply calculate the corresponding public key (which we already do in dsa_set_key)

uhm, we can still change that if it makes sense... and you meant `dh_set_key()`!?

TBH I also thought about it, but then forgot to ask you...

**Comment by karel-m** [comment]
Yes `dh_set_key` but actually it can be applied to `dsa_set_key` as well (in both cases it is just a simple `mp_exptmod`).

**Comment by sjaeckel** [comment]
feel free to open a PR, we'll put that still in 1.18
