### ISSUE TITLE
L parameter for CCM

### ISSUE THREAD

**Issue by s09bQ5** [libtom/libtomcrypt#252]
If I understand RFC3610 correctly, L can be chosen freely as long as it allows the payload size to be encoded. But the current implementation of ccm_init uses the minimal value for L that can encode the payload size. So right now libtomcrypt can not be used to decrypt CCM messages that use an L that is bigger than necessary. In OpenSSL L defaults to 8 and can be changed to any allowed value.

**Comment by karel-m** [comment]
If I understand our implementation correctly you can "choose" `L` indirectly by choosing `nonce` of proper lenth: `L = 15 - length(nonce)` where `7 <= lenght(nonce) <= 13`

**Comment by s09bQ5** [comment]
Oh, you are right, ccm_add_nonce increases L or truncates the nonce depending on its size.
Sorry for the noise.
