### ISSUE TITLE
warning: missing braces (again)

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#259]
Same as #242 but this time with gcc 4.9.2 on a quite recent system

```
$ uname -a
Linux debian-armel 3.16.0-4-versatile #1 Debian 3.16.39-1+deb8u1 (2017-02-22) armv5tejl GNU/Linux

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabi/4.9/lto-wrapper
Target: arm-linux-gnueabi
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armel --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv4t --with-float=soft --enable-checking=release --build=arm-linux-gnueabi --host=arm-linux-gnueabi --target=arm-linux-gnueabi
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)
```

The warning:
```
cc -Isrc/headers -Itests -DLTC_SOURCE -Wall -Wextra -Werror -DUSE_LTM -DLTM_DESC -DLTC_SOURCE -Isrc/headers -I../libtommath -c demos/timing.c -o demos/timing.o
demos/timing.c: In function 'time_rsa':
demos/timing.c:704:4: error: missing braces around initializer [-Werror=missing-braces]
    unsigned char buf[2][2048] = { 0 };
    ^
demos/timing.c:704:4: error: (near initialization for 'buf[0]') [-Werror=missing-braces]
demos/timing.c: In function 'time_ecc':
demos/timing.c:935:4: error: missing braces around initializer [-Werror=missing-braces]
    unsigned char buf[2][256] = { 0 };
    ^
demos/timing.c:935:4: error: (near initialization for 'buf[0]') [-Werror=missing-braces]
cc1: all warnings being treated as errors
makefile.unix:242: recipe for target 'demos/timing.o' failed
```

I only want to say that the information that it might be related only to old gcc 3.x is not quite correct.

**Comment by rofl0r** [comment]
as is visible from the bugreport i linked in #242 ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 ) the issue was fixed during GCC 4.9/5.0 development cycle. i believe it is fixed in 4.9.3 already, but the first fixed version might even have been 5.0.
that doesn't change the fact that the warning is/was a compiler bug to begin with.
what i refered to in #242 regarding GCC3 was only that GCC3 is so old i didn't bother to backport the patch (i did so for gcc 4.7.x and gcc 4.8.x).

**Comment by sjaeckel** [comment]
how about adding `-Wno-missing-braces`? :)

**Comment by buggywhip** [comment]
> On 7Aug, 2017, at 1:11 PM, Steffen Jaeckel <notifications@github.com> wrote:
> 
> how about adding -Wno-missing-braces? :)
> 
upper or lower?  ;-)

**Comment by buggywhip** [comment]
> On 7Aug, 2017, at 1:13 PM, Larry Bugbee <bugbee@mac.com> wrote:
> 
> 
>> On 7Aug, 2017, at 1:11 PM, Steffen Jaeckel <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> how about adding -Wno-missing-braces? :)
>> 
> upper or lower?  ;-)

Seriously, I did the following on my local copy.

Replaced timing.c line 704 with
    unsigned char buf[2][2048] = { {0} };
and line 935 with
    unsigned char buf[2][256] = { {0} };

**Comment by apjanke** [comment]
The double-braces kind of make sense, since you're initializing an array of arrays, and not just a flat array.

**Comment by sjaeckel** [comment]
The only correct solution is what @rofl0r already wrote.

**Comment by sjaeckel** [comment]
I guess the solution of #283 solves this as well

**Comment by karel-m** [comment]
Before closing this issue we should clearly state that:

**`= { 0 }` is the right way to zero-initialize**
