### ISSUE TITLE
`make test` failure on macOS for 1.18.0-rc3

### ISSUE THREAD

**Issue by apjanke** [libtom/libtomcrypt#281]
Hi, libtom folks,

In libtomcrypt 1.18.0-rc3, the `make test` is failing for me, with an undefined symbol error. I'm using `makefile.unix`, and the main build succeeds, but the `make test` build fails at the link stage, with the following error.

```
$ make -f makefile.unix CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/lib" EXTRALIBS="-ltommath" test
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/base64_test.c -o tests/base64_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/cipher_hash_test.c -o tests/cipher_hash_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/common.c -o tests/common.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/der_test.c -o tests/der_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/dh_test.c -o tests/dh_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/dsa_test.c -o tests/dsa_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/ecc_test.c -o tests/ecc_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/file_test.c -o tests/file_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/katja_test.c -o tests/katja_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/mac_test.c -o tests/mac_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/misc_test.c -o tests/misc_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/modes_test.c -o tests/modes_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/mpi_test.c -o tests/mpi_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/multi_test.c -o tests/multi_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/no_prng.c -o tests/no_prng.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/pkcs_1_eme_test.c -o tests/pkcs_1_eme_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/pkcs_1_emsa_test.c -o tests/pkcs_1_emsa_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/pkcs_1_oaep_test.c -o tests/pkcs_1_oaep_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/pkcs_1_pss_test.c -o tests/pkcs_1_pss_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/pkcs_1_test.c -o tests/pkcs_1_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/prng_test.c -o tests/prng_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/rotate_test.c -o tests/rotate_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/rsa_test.c -o tests/rsa_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/store_test.c -o tests/store_test.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/lib -c tests/test.c -o tests/test.o
cc tests/base64_test.o tests/cipher_hash_test.o tests/common.o tests/der_test.o tests/dh_test.o tests/dsa_test.o tests/ecc_test.o tests/file_test.o tests/katja_test.o tests/mac_test.o tests/misc_test.o tests/modes_test.o tests/mpi_test.o tests/multi_test.o tests/no_prng.o tests/pkcs_1_eme_test.o tests/pkcs_1_emsa_test.o tests/pkcs_1_oaep_test.o tests/pkcs_1_pss_test.o tests/pkcs_1_test.o tests/prng_test.o tests/rotate_test.o tests/rsa_test.o tests/store_test.o tests/test.o libtomcrypt.a  -ltommath -o test
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _der_test in der_test.o
      _der_flexi_test in der_test.o
      _der_choice_test in der_test.o
      __prime_test in dh_test.o
      __dhparam_test in dh_test.o
      __set_test in dh_test.o
      _ecc_test_shamir in ecc_test.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1
```

The symbol does seem to be defined in the library:

```
$ nm libtomcrypt.a | grep _ltc_mp | grep --context=2 C
                 U _ltc_mp
libtomcrypt.a(crypt_ltc_mp_descriptor.o):
00000000000001a0 C _ltc_mp
                 U _ltc_mp
                 U _ltc_mp
```

This is on:
* macOS 10.12.6
* libtommath 1.0.1 installed via Mac Homebrew

Any idea what's going on here? Or any additional info I can provide to help debug?

**Comment by apjanke** [comment]
One other data point: if I rebuild the entire thing using `gmake` and GCC by modifying the main `makefile` to run on Darwin, then it succeeds. (I installed `gmake` on Mac via Homebrew here, with `brew install make`.)

```
$ gmake clean
[...]
$ gmake
[...]
$ gmake test
[...]
   * gcc tests/test.o
   * gcc test
$ ./test
[...]
NO math provider selected, all tests requiring MPI were disabled and will 'nop'
[...]
SUCCESS: passed=10 failed=0 nop=11 duration=0.0sec real=0.0sec
```

Looks like an interaction with the `CFLAGS` needed to get the generic `makefile.unix` to work on Mac. If I pass them in to the `gmake; gmake test` build, it fails with the same error.

The generic `makefile.unix` defines `-DUSE_LTM -DLTM_DESC` by default, and it doesn't appear that the main `makefile` does; this may be what's making the difference here.

```
CFLAGS    = -O2 -DUSE_LTM -DLTM_DESC -I../libtommath
```

If I set those flags using `gmake`, then I get the same error, in addition to a few others.

```
$ gmake CFLAGS="-DUSE_LTM -DLTM_DESC" test
   * gcc tests/base64_test.o
   * gcc tests/cipher_hash_test.o
[...]
Package libtommath was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtommath.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtommath' found
   * gcc test
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _der_test in der_test.o
      _dh_test in dh_test.o
      _ecc_test_shamir in ecc_test.o
      _pkcs_1_eme_test in pkcs_1_eme_test.o
      _pkcs_1_emsa_test in pkcs_1_emsa_test.o
      _pkcs_1_oaep_test in pkcs_1_oaep_test.o
      _pkcs_1_pss_test in pkcs_1_pss_test.o
      ...
[...]
```

**Comment by apjanke** [comment]
(BTW, the main `makefile` seems to work fine with the system `make` on macOS 10.12.6, which comes with GNU Make 3.81.)

**Comment by buggywhip** [comment]
FWIW, on an iMac running macOS 10.12.6 with Apple LLVM version 8.1.0 (clang-802.0.42) I am able to build everything using 
      make -j5 -f makefile.shared CFLAGS="-DUSE_TFM -DTFM_DESC -I/usr/local/include" EXTRALIBS="-L/usr/local/lib -ltfm" all  
My biggest issue had to do with libtool vs glibtool which was addressed.

That said...

Running the same command against makefile.unix I get the same error as Andrew.
      Undefined symbols for architecture x86_64:
        "_ltc_mp", referenced from:

Poking around I found ltc_mp defined as extern in headers/tomcrypt_math.h and again normally in misc/crypt/crypt_ltc_mp_descriptor.c  My C being rusty and not being intimately familiar with the nuances of libtomcrypt's architecture, I'm not sure of the proper fix.  Nevertheless, after removing the word extern in tomcrypt_math.h the build completed normally and ./test ran as did timing and tv_gen. (Note: libtomcrypt.a was built but libtomcrypt.dylib was not.  For that you will need to run against makefile.shared.)

And yes, for consistency we should add sizes and constants to makefile.unix's target list.

**Comment by karel-m** [comment]
The difference between `makefile` and `makefile.unix` is that
*  `make all` (using `makefile`) - builds the library but skips all parts requiring maths stuff (ltm, tfm)
*  `make -f makefile.unix all` - without any extra parameters most likely fails as by default it expects libtommath library in `../libtommath/`

The idea of making `make all && make test` to build+test at least something was introduced quite recently (credits goes to @buggywhip) in one of the release candidates. I am a bit reluctant to replicate this behaviour in `makefile.(unix|mingw|msvc)` as we are very close to the release and we can introduce new bugs (re-testing those makefiles on exotic platforms / exotic make tools / exotic compilers will take some time).

I am not a MacOS user but perhaps @apjanke may help us to track down why the main `makefile` fails to build static library on MacOS. If we fix this then there will be no need to use `makefile.unix` on MacOS.

**Comment by apjanke** [comment]
Building from `makefile.shared` using your command works for me too. 

> Nevertheless, after removing the word extern in tomcrypt_math.h the build completed normally and ./test ran as did timing and tv_gen. 

Based on my reading of the source, that seems like it's redefining the symbol in the `test.o` object being built for `test`, which would replace the symbol that should be coming from `crypt_ltc_mp_descriptor.o`. From what I know, it's pretty unusual for a header file to define a non-extern symbol with storage. Which suggests to me that the linker is not picking up the `_ltc_mp` symbol in the `libtomcrypt.a` archive.

For the shared files, looks like you're building against a shared-lib `libtomsfastmath`, where I'm building against a static-lib `libtommath`. I'll try building a shared-lib `libtommath` to remove one of the variables here, and see if we can narrow it down to how the linkage with static libraries is working. I wouldn't think that's an issue, though, since this symbol is coming from within `libtomcrypt`.

**Comment by apjanke** [comment]
> I am not a MacOS user but perhaps @apjanke may help us to track down why the main makefile fails to build static library on MacOS.

I can sure try. The linkage issues with `makefile` and `makefile.unix` look the same to me, at this point. For example, when providing the options to use `libtommath` to `makefile.unix`, it's still blowing up.

```

$ make -j8 -f makefile.unix CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
cc demos/hashsum.o libtomcrypt.a  /usr/local/lib/libtommath.a -o hashsum
cc demos/ltcrypt.o libtomcrypt.a  /usr/local/lib/libtommath.a -o ltcrypt
cc demos/small.o libtomcrypt.a  /usr/local/lib/libtommath.a -o small
cc demos/tv_gen.o libtomcrypt.a  /usr/local/lib/libtommath.a -o tv_gen
cc demos/timing.o libtomcrypt.a  /usr/local/lib/libtommath.a -o timing
cc tests/base64_test.o tests/cipher_hash_test.o tests/common.o tests/der_test.o tests/dh_test.o tests/dsa_test.o tests/ecc_test.o tests/file_test.o tests/katja_test.o tests/mac_test.o tests/misc_test.o tests/modes_test.o tests/mpi_test.o tests/multi_test.o tests/no_prng.o tests/pkcs_1_eme_test.o tests/pkcs_1_emsa_test.o tests/pkcs_1_oaep_test.o tests/pkcs_1_pss_test.o tests/pkcs_1_test.o tests/prng_test.o tests/rotate_test.o tests/rsa_test.o tests/store_test.o tests/test.o libtomcrypt.a  /usr/local/lib/libtommath.a -o test
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _ecc_gen in tv_gen.o
      _main in tv_gen.o
      _ltc_init_multi in libtomcrypt.a(multi.o)
      _ltc_deinit_multi in libtomcrypt.a(multi.o)
      _ltc_cleanup_multi in libtomcrypt.a(multi.o)
      _ltc_ecc_map in libtomcrypt.a(ltc_ecc_map.o)
      _ltc_ecc_mul2add in libtomcrypt.a(ltc_ecc_mul2add.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _main in timing.o
      _time_mult in timing.o
      _time_sqr in timing.o
      _dh_generate_key in libtomcrypt.a(dh_generate_key.o)
      _dh_set_pg in libtomcrypt.a(dh_set.o)
      _dh_set_pg_groupsize in libtomcrypt.a(dh_set.o)
      _dh_set_key in libtomcrypt.a(dh_set.o)
      ...
ld: symbol(s) not found for architecture x86_64
make: *** [tv_gen] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [timing] Error 1
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _der_test in der_test.o
      _der_flexi_test in der_test.o
      _der_choice_test in der_test.o
      __prime_test in dh_test.o
      __dhparam_test in dh_test.o
      __set_test in dh_test.o
      _ecc_test_shamir in ecc_test.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1
```

I'll focus on trying to get it to work under the main `makefile`.

**Comment by apjanke** [comment]
BTW, is the reason that the main `makefile` balks on Mac because of this static-library-building error? Or is it that the build file itself requires a recent GNU Make, and doesn't think that macOS has it?

In other words, could this platform test:

```
ifneq ($(MAKECMDGOALS),clean)
ifeq ($(PLATFORM), Darwin)
$(error Known to not work on Mac, please use makefile.unix for static libraries or makefile.shared for shared libraries)
endif
endif
```

be replaced by a test against `$(.FEATURES)` or something similar?

**Comment by buggywhip** [comment]
On macOS...  I just got the main makefile to build libtomcrypt.a and the only "change" was to remove the word extern fm tomcrypt_math.h, line 492.  Is there a better fix?

**Comment by karel-m** [comment]
Before:
```
make -j8 -f makefile.unix CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
```

You need to run: `make clean`

**Comment by buggywhip** [comment]
I did but did again just to be sure.  It worked.  ...with the extern deletion.

**Comment by apjanke** [comment]
> On macOS...  I just got the main makefile to build libtomcrypt.a and the only "change" was to remove the word extern fm tomcrypt_math.h, line 492.  Is there a better fix?

`libtomcrypt.a` builds regardless. It's only when it gets to building `test` that it errors out here. I think it's a problem with linking the built `libtomcrypt.a` into the `test` binary. It's only at the final linking to an executable that all symbols need to be resolved, I think, and that's where the error occurs.

**Comment by buggywhip** [comment]
After a clean, make test and ./test worked.  ...with the deletion.  bc I didn't specify a math lib, I got nops as expected.

**Comment by apjanke** [comment]
Same thing happens if I do a `make clean` first. I think the only difference here is that I'm now doing `make ... all`, which includes `test`, instead of a plain `make ...` with the default target, which only builds the library. In all cases, the static library builds for me; it's only when I try to build an executable that it errors out.

```
$ make clean
find . -type f    -name "*.o"   \
               -o -name "*.lo"  \
               -o -name "*.a"   \
               -o -name "*.la"  \
               -o -name "*.obj" \
               -o -name "*.lib" \
               -o -name "*.exe" \
               -o -name "*.dll" \
               -o -name "*.so"  \
               -o -name "*.gcov"\
               -o -name "*.gcda"\
               -o -name "*.gcno"\
               -o -name "*.il"  \
               -o -name "*.dyn" \
               -o -name "*.dpi"  | xargs rm -f
rm -f  test small tv_gen ltcrypt sizes constants hashsum openssl-enc timing
rm -f *_tv.txt
rm -f *.pc
rm -rf `find . -type d -name "*.libs" | xargs`
/Applications/Xcode-8.3.3.app/Contents/Developer/usr/bin/make -C doc/ clean
rm -f *.dvi *.log *.aux *.toc *.idx *.ilg *.ind *.out *.lof
rm -rf doxygen/
[~/local/repos/libtomcrypt on ⇄ build-on-mac-darnit ±]
$ make -j8 -f makefile.unix CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -DENCRYPT_ONLY -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes_enc.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -c src/ciphers/anubis.c -o src/ciphers/anubis.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -c src/ciphers/blowfish.c -o src/ciphers/blowfish.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -c src/ciphers/camellia.c -o src/ciphers/camellia.o
[...]
cc demos/hashsum.o libtomcrypt.a  /usr/local/lib/libtommath.a -o hashsum
cc demos/ltcrypt.o libtomcrypt.a  /usr/local/lib/libtommath.a -o ltcrypt
cc demos/small.o libtomcrypt.a  /usr/local/lib/libtommath.a -o small
cc demos/tv_gen.o libtomcrypt.a  /usr/local/lib/libtommath.a -o tv_gen
cc demos/timing.o libtomcrypt.a  /usr/local/lib/libtommath.a -o timing
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _main in timing.o
      _time_mult in timing.o
      _time_sqr in timing.o
      _dh_generate_key in libtomcrypt.a(dh_generate_key.o)
      _dh_set_pg in libtomcrypt.a(dh_set.o)
      _dh_set_pg_groupsize in libtomcrypt.a(dh_set.o)
      _dh_set_key in libtomcrypt.a(dh_set.o)
      ...
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_ltc_mp", referenced from:
      _ecc_gen in tv_gen.o
      _main in tv_gen.o
      _ltc_init_multi in libtomcrypt.a(multi.o)
      _ltc_deinit_multi in libtomcrypt.a(multi.o)
      _ltc_cleanup_multi in libtomcrypt.a(multi.o)
      _ltc_ecc_map in libtomcrypt.a(ltc_ecc_map.o)
      _ltc_ecc_mul2add in libtomcrypt.a(ltc_ecc_mul2add.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [timing] Error 1
make: *** Waiting for unfinished jobs....
make: *** [tv_gen] Error 1
```

And yeah, these errors only happen for me when I specify a math lib, too. But that's a case that should be supported, right?

**Comment by apjanke** [comment]
This smells to me like it's related to the `-Wl,--whole-archive` option, which is used in the `COVERAGE=1` case here and (I think) needed to combine multiple static `.a` libraries into one. But it's not supported by macOS's ld, and I don't know what the right alternative is.

**Comment by buggywhip** [comment]
> After a clean, make test and ./test worked. ...with the deletion. bc I didn't specify a math lib, I got nops as expected.

And, specifying tfm worked and ./test provided times for rsa, dsa, etc.

Is there a short explanation for the necessity of the extern?

**Comment by apjanke** [comment]
> Is there a short explanation for the necessity of the extern?

The "extern" just means it's a reference to a symbol defined in another compilation unit (source file). Sort of like a forward declaration or function prototype. When you remove the `extern`, then the declaration becomes a definition that actually creates that symbol in the current compilation unit (source file) and allocates storage for it there.

That's why having a non-`extern` definition in a header file is unusual: if multiple `.c` files were to include that header, with a non-`extern` definition of that symbol, they'd each declare and allocate a global symbol of that name in their compilation units, and then there would be conflicts if you tried to link them together.

Sorry if I'm not using quite the right terminology here. But basically, when you have the `extern`, it's like a function prototype, and without the `extern`, it's like a full function definition. But for a global variable instead of a function.

**Comment by buggywhip** [comment]
> On 31Aug, 2017, at 12:35 AM, Andrew Janke <notifications@github.com> wrote:
> 
> Is there a short explanation for the necessity of the extern?
> 
> The "extern" just means it's a reference to a symbol defined in another compilation unit (source file). Sort of like a forward declaration or function prototype. When you remove the extern, then the declaration becomes a definition that actually creates that symbol in the current compilation unit (source file) and allocates storage for it there.
> 
> That's why having a non-extern definition in a header file is unusual: if multiple .c files were to include that header, with a non-extern definition of that symbol, they'd each declare and allocate a global symbol of that name in their compilation units, and then there would be conflicts if you tried to link them together.
> 
> Sorry if I'm not using quite the right terminology here. But basically, when you have the extern, it's like a function prototype, and without the extern, it's like a full function definition. But for a global variable instead of a function.
> 
no apology needed.  I get it, now.  I was overlooking the possibility of multiple defs.  Much appreciated, thanks.

**Comment by apjanke** [comment]
Here's a wacky theory: that global `ltc_mp` variable is declared in `src/headers/tomcrypt_math.h`, and defined in `src/misc/crypt/crypt_ltc_mp_descriptor.c`, but it is not actually *initialized*. It is conditionally assigned to in `src/misc/crypt/cript_inits.c`, but I'm not sure that's technically the same thing as being initialized. Maybe the compiler (`clang` in this case, since on macOS, the system `gcc` is just a front-end to Clang, not GCC) is leaving it unallocated, due to an area of "undefined" behavior in the C spec or a compiler bug.

Here's the definition in `src/misc/crypt/crypt_ltc_mp_descriptor.c`.
```
ltc_math_descriptor ltc_mp;
```

If I add an initialization to it like this:

```
/* Initialize ltc_mp to nulls, to force allocation on all platforms, including macOS. */
ltc_math_descriptor ltc_mp ={ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
```

Then everything, including the test programs, builds and runs. And notice that the symbol in `libtomcrypt.a` is now an `S` instead of a `C` (common/uninitialized).

```
$ nm libtomcrypt.a | grep ltc_mp | grep -v U
libtomcrypt.a(crypt_ltc_mp_descriptor.o):
0000000000000000 S _ltc_mp
```

Build output excerpt:

```
$ make -j8 -f makefile.unix CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes.o
cc -Isrc/headers -Itests -DLTC_SOURCE -DUSE_LTM -DLTM_DESC -I/usr/local/include -DENCRYPT_ONLY -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes_enc.o
[...]
$ ./test
build == Undefined version
LibTomCrypt 1.18.0-rc3 (www.libtom.net)
LibTomCrypt is public domain software.
[...]
math provider = libtommath
MP_DIGIT_BIT = 60
[...]
SUCCESS: passed=20 failed=0 nop=1 duration=18.4sec real=18.4sec
$
```

And it works with the main `makefile`, too.

```
$ make -j8 CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
[...]

$ ./test
build == git-v1.18.0-rc3-12-g9ea6247-dirty
LibTomCrypt 1.18.0-rc3 (www.libtom.net)
LibTomCrypt is public domain software.
[...]
math provider = libtommath
[...]

SUCCESS: passed=20 failed=0 nop=1 duration=17.4sec real=17.4sec
$
```

**Comment by apjanke** [comment]
Added a suggested fix in #283.

**Comment by karel-m** [comment]
Ad makefile.unix

This should work (providing you have libtommath in /usr/local):
```
make -f makefile.unix clean
make -f makefile.unix -j8 CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
```

otherwise there is a bug

**Comment by apjanke** [comment]
I think there's a bug here, or at least an issue with the source code's interaction with `clang`. I ran those exact commands:

```
make -f makefile.unix clean
make -f makefile.unix -j8 CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS=/usr/local/lib/libtommath.a all
```

using `makefile.unix` (except for the `make clean`), and it came up with the same linker errors.

Here's a Gist of my entire build output: https://gist.github.com/apjanke/93466d802e0c01932327eadd1374465e

**Comment by karel-m** [comment]
Could you try it with the patch #283 ?

**Comment by apjanke** [comment]
Works correctly with the patch: the build succeeds, and `./test` passes.

Entire build output for running with the patch:
https://gist.github.com/apjanke/f598bbb3e0c1ea5016d4f2da39de2fae

**Comment by karel-m** [comment]
I am closing this issue. Let's move the discussion to #283.
