### ISSUE TITLE
DSA dependency on RSA

### ISSUE THREAD

**Issue by andrew-boyarshin** [libtom/libtomcrypt#285]
I am building heavily trimmed down libtomcrypt library (SHA, DSA & PRNG only) and encountered unexpected dependency. I believe _dsa_import.c:89_ should use `LTC_DER_MAX_PUBKEY_SIZE`, not `MAX_RSA_SIZE`, because DSA depends on ASN.1/DER, not RSA. It also matches context (length of public key buffers). It is also the only DSA dep on RSA.

https://github.com/libtom/libtomcrypt/blob/87f94e1f0d141d20816bf71fea329d5d070265ec/src/pk/dsa/dsa_import.c#L84-L95

It is also confirmed by comment:

https://github.com/libtom/libtomcrypt/blob/87f94e1f0d141d20816bf71fea329d5d070265ec/src/headers/tomcrypt_custom.h#L440-L451

**Comment by karel-m** [comment]
Now fixed in release/1.18.0 branch.

Thanks for the report.
