### ISSUE TITLE
version 1.18.0 SONAME

### ISSUE THREAD

**Issue by sjaeckel** [libtom/libtomcrypt#300]
While passing the RC4 to several distros it was discovered that the libraries' ABI version should be bumped to `1:0` because of the modified structs. That was discovered while testing against dropbear.

Is there a reason we should invest time to keep 1.18.0 ABI compatible?

One reason could be that our plans to further extend the library would lead to an ABI `2:0` in the next release...

I'm now highlighting some persons whose opinion I'd like to hear resp. a :+1: for okay to bump.

@apjanke 
@buggywhip 
@fperrad 
@jforissier (I guess you don't care about the ABI version as you're always static linking :) )
@karel-m 
@lvc 
@mkj 
@rofl0r 
@stapelberg 

The persons mentioned can happily trigger more people to vote.

**Comment by stapelberg** [comment]
In Debian, we have chrony and dropbear to link against the new ABI version, i.e. the effort is quite small. No objection from my end to the ABI change, hence.

**Comment by jforissier** [comment]
@sjaeckel as you said exactly!

**Comment by rofl0r** [comment]
you should definitely bump the soname, there have been so many changes that trying to pretend the ABI is still unchanged would be a huge lie.
