### ISSUE TITLE
Need PDF format for documentation

### ISSUE THREAD

**Issue by kutran** [libtom/libtomcrypt#305]
Please have the PDF version of the document as specified in the README.

**Comment by buggywhip** [comment]
> On 2Oct, 2017, at 10:43 AM, Kuniaki Tran <notifications@github.com> wrote:
> 
> Please have the PDF version of the document as specified in the README.
> 
Try pulling RC5, not the 1.18.0 branch.

http://www.libtom.net/news/LTC_1.18RC5/



.

**Comment by sjaeckel** [comment]
Try https://github.com/libtom/libtomcrypt/releases/download/v1.18.0-rc5/crypt-1.18.0-rc5.pdf
