### ISSUE TITLE
Requirement of ECC and RSA functionality with TomFastMath

### ISSUE THREAD

**Issue by hmnsh18** [libtom/libtomcrypt#336]
### Description

[Description of the Query]
Dear LibTomCrypt team,

I am working on a requirement to implement the RSA as well as ECC functionality simultaneously in an embedded platform. I have a total RAM size of 24 KBytes. Since libtomfast math required to fix the size of fixed point integer the compile time, I am facing a memory constraint issue of running ECC and RSA together. I am able to run both RSA and ECC separately in my embedded platform. Only for RSA implementation, I have set the size of "FP_MAX_SIZE"  to 4096 bits in Tom Fast Math. In this case, I am able to meet my memory requirement and worst case usage of heap memory is approx 8 Kbytes. For ECC functionality, I have set the size of "FP_MAX_SIZE"  to 1152 bits in Tom Fast Math.  In case of ECC, worst case memory usage comes out to be 14 Kbytes while running the "ecc_tests" function. So separately, I am able to implement both functionality. But the problem comes when I try to run both together. In this case, I have to keep the value of  "FP_MAX_SIZE" to 4096 bits because of RSA. Because of this, memory usage of ECC will reach to approximately 56 KBytes. 

Is there any smart way to tackle this problem?

 I was thinking of changing the following declaration 
from:
"/* a FP type */
typedef struct {
    fp_digit dp[FP_SIZE];
    int      used,
             sign;
} fp_int

to:

/* a FP type */
typedef struct {
    fp_digit* dp;
    int      used,
             sign;
} fp_int

By doing the above change,  wherever I define the variable of type fp_int, I will dynamically allocate the fixed size memory of 4096 bits to dp for RSA and 1152 bits for ECC. It can be ensured that at one time either ECC or RSA functionality will run. Am I thinking in the right direction? 
Am I able to explain my problem clearly? If not, please let me know and we can further discuss on this.

Regards
Himanshu

**Comment by sjaeckel** [comment]
Cool, that could be the missing implementation of https://github.com/libtom/tomsfastmath/issues/10 nobody really has time for...


> Only for RSA implementation, I have set the size of "FP_MAX_SIZE" to 4096 bits in Tom Fast Math.

I hope you're aware that this limits the RSA keys you will be able to handle to maximum 2048 bits.

> By doing the above change, wherever I define the variable of type fp_int, I will dynamically allocate the fixed size memory of 4096 bits to dp for RSA and 1152 bits for ECC

You shouldn't do it statically but allocate dp of the MPI's dynamically to something near the really required size.

> It can be ensured that at one time either ECC or RSA functionality will run

Okay, you could also allocate it statically sized, but still... if you would do it dynamically you would have a solution that works for both cases in parallel (as long as there's enough memory :) )


In general I'd say you're on the right track.

**Comment by hmnsh18** [comment]
Hi Steffen,
Thank you for replying.
One thing I forgot to mention that I have written customized Malloc and
Free functions which allocates and deallocates the memory from big sized
static array. This implementation is very short and simple. The only
limitation is that all the memory allocated should be cleared in LIFO
format i.e the last allocated memory should be freed first.
Since, my application is single thread so this approach works fine for me
and it is very optimized for embedded applications. Because of this
constraint, I had to modify the code in ECC and RSA files to free the
memory in the reverse sequence in the way it was allocated. As I said
earlier that I am able to run both RSA and ECC functionalities.

My next aim is to run both RSA and ECC functionalities simultaneously by
modifying the fp_int structure.

I will try to work on my approach and will let you know the results.

Regards
Himanshu

**Comment by sjaeckel** [comment]
> I had to modify the code in ECC and RSA files to free the
> memory in the reverse sequence in the way it was allocated.

cool, PR for that would be welcome
