### ISSUE TITLE
ECC improvements

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#34]
Hi,

I would like to propose a set of changes to ECC part of libtomcrypt. I have already implemented all proposed changes in my something-like-fork of libtomcrypt which is available https://github.com/DCIT/perl-CryptX/tree/master/src/ltc
## 1/ Support for curves y^2 = x^3 + a*x + b

Currently libtomcrypt supports only y^2 = x^3 - 3*x + b. 

Support for general case required changes to ltc_ecc_projective_dbl_point(), ltc_ecc_projective_add_point() and ltc_ecc_is_point() as you can see in my repo (please note that I have moved is_point function into a separate file ltc_ecc_is_point.c). Extending ltc_ecc_set_type + other small changes were also necessary.
## 2/ Support for compressed public keys

Already existing function ecc_ansi_x963_export() allows you to export EC public key in a format defined by X9.63 but only supports 'uncompressed' form.

I have added support for exporting compressed EC public keys (which was easy) as well as for import. The import part was a bit tricky as it was necessary to add mp_sqrtmod_prime to libtommath.

As I wanted to keep old interface I have created new functions:
- https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/pk/ecc/ecc_export_raw.c
- https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/pk/ecc/ecc_import_raw.c

NOTE: The new functions ecc_import_raw() / ecc_export_raw() also support import/export of private key (raw octects)

My implementation of mp_sqrtmod_prime (based on Tonelli–Shanks algorithm) is available here:
- https://github.com/DCIT/perl-CryptX/blob/master/src/ltm/bn_mp_sqrtmod_prime.c
## 3/ DER format compatible with openssl

To support importing/exporting keys in DER format compatible with openssl we need to support the following:
- private key format: http://tools.ietf.org/html/rfc5915
- public key format: http://tools.ietf.org/html/rfc5480

Again, I wanted to keep old interface so I have created new functions:
- https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/pk/ecc/ecc_import_full.c
- https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/pk/ecc/ecc_export_full.c

A small trouble was with adding support for OPTIONAL items in ASN.1 sequences. A big trouble was with private keys which uses ASN.1 context specific tags which are not supported by current libtomcrypt. This part is more a hack/workaround than a systematic support but fully follow ASN.1 specification is not easy.

See the changes at https://github.com/DCIT/perl-CryptX/commits/master/src/ltc/pk/asn1

As my changes to libtomcrypt + libtommath are are quite huge I am not sending them as a pull request. However if you find it worth to be included in upstream libtomcrypt I can fork develop branch a port my changes (I mean those you will agree with) into it.

Any feedback welcome.

Karel

**Comment by karel-m** [comment]
Hi,

I have rebased all proposed changes on top of the current develep and pushed them into a new branch for review
* branch - https://github.com/libtom/libtomcrypt/tree/miko-ecc-enhancements
* changes - https://github.com/libtom/libtomcrypt/commit/9a4a138b96

Keep in mind that the new features requires libtommath with a new function `mp_sqrtmod_prime` as I have proposed here https://github.com/libtom/libtommath/issues/33

**Comment by tomstdenis** [comment]
IIRC point compression is subjected to patents.  I'd highly recommend leaving that disabled by default.

**Comment by sjaeckel** [comment]
I don't know if this is the patent you are thinking of, or if there are others, but at least one patent targeting point compression is expired:
http://cr.yp.to/patents/us/6141420.html

**Comment by sjaeckel** [comment]
@karel-m can you please create a PR from that branch?

**Comment by sjaeckel** [comment]
mh, travis won't be able to build as it requires new functionality in ltm

btw. would you mind creating an implementation of `mp_sqrtmod_prime()` for tfm? and is that functionality available in gmp?

**Comment by tomstdenis** [comment]
I didn't have a specific # in mind but we never implemented it originally (nor in my private work) because of noise surrounding it (and quite frankly it rarely comes up with customers).

**Comment by karel-m** [comment]
Ad @sjaeckel 's questions:
* as for creating pull request see https://github.com/libtom/libtomcrypt/pull/65
* as for tfm implementation of `mp_sqrtmod_prime()` I can try it but to be honest I haven't use tfm yet :)
* as for gmp I have no idea, I have googled this https://github.com/martani/Quadratic-Sieve-Cxx/blob/master/src/gmp-patch.c (GPL)

However there are more TODOs:
* documentation
* tests

As for the tests I have a bunch of test data and test vectors in my perl module based on libtommath + libtomcrypt (+my patches) - see https://github.com/DCIT/perl-CryptX/tree/master/t - that is why I am pretty confident that my implementations is more-or-less correct (at least it is interoperable with openssl's ec). It might be a good idea to add some tests to libtomcrypt.

**Comment by karel-m** [comment]
Ad GMP implementation probably this thread https://gmplib.org/list-archives/gmp-discuss/2013-April/005300.html is interesting (which I am BTW referencing in my source code so it was an inspiration for my implementation:)

**Comment by karel-m** [comment]
FYI, I have temporarily disabled mp_sqrtmod_prime by this commit https://github.com/libtom/libtomcrypt/commit/c1d9ba47d1 to make Travis-CI happy.

Now I need to analyze/fix some failing tests e.g. https://travis-ci.org/libtom/libtomcrypt/jobs/59052973

**Comment by karel-m** [comment]
Another special ifdef to make Travis-CI pass build + tests https://github.com/libtom/libtomcrypt/commit/4ee93c7e99 The hack with `#ifdef LTM_SUPPORTS_MP_SQRTMOD_PRIME_XXX_DEBUG_ONLY_XXX` is currently at two places.

I have also skipped newly added curves in tv_gen (as currently we do not have corresponding test vectors in notes/ecc_tv.txt) - see https://github.com/libtom/libtomcrypt/commit/523a9047f16f86 - after we fix the code we have to regenerate notes/ecc_tv.txt for all curves.

Anyway, Travis-CI is all green now.

**Comment by karel-m** [comment]
Considering that this issue was tagged as `v2.0.0` there is an opportunity to rethink the ECC interface a bit. I have tried in my patch to be as much backwards compatible as possible but there are definitely some places that can be made more elegant if we will not strictly require 100% backcompat.

**Comment by sjaeckel** [comment]
Then we should think about it!
Do you already have an idea of what should be changed?
Btw. the 2.0.0 is required because we will have a changed ABI, so why not changing the API if it makes sense... but we should also think if we could probably still provide some layer of compatibility!?!

**Comment by rkreicbergs** [comment]
Btw, MR-initializing a (when a!=-3) could help to avoid mp_mulmod() in every ptmul iteration.

**Comment by karel-m** [comment]
> Btw, MR-initializing a (when a!=-3) could help to avoid mp_mulmod() in every ptmul iteration.

@rkreicbergs could you please elaborate your idea?

**Comment by rkreicbergs** [comment]
@karel-m Can you please send a link to your current ptmul implementation? It's been a long time and I can't find it again... :) I can then comment on the exact code.

**Comment by karel-m** [comment]
perhaps these:
* https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ltc_ecc_mulmod.c
* https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ltc_ecc_mulmod_timing.c

**Comment by rkreicbergs** [comment]
@karel-m Can you point me to the implementation of ecc_ptdbl()? I remember there was some trick to locate it... :)

The Q - is a initialized for Montgomery Multiplication? AFAIR, it was used mp_mulmod() in ecc_ptdbl() - using Montgomery Reduction instead could be more efficient. Thought probably not by much.

**Comment by karel-m** [comment]
ecc_ptdbl - https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ltc_ecc_projective_dbl_point.c

**Comment by rkreicbergs** [comment]
@karel-m yes, that's it, thank you!

If `a!=3`, you currently do mulmod in `ltc_ecc_projective_dbl_point()` (within each iteration of `ltc_ecc_mulmod()` main loop):
`if ((err = mp_mulmod(t2, a, modulus, t1)) != CRYPT_OK)                      { goto done; }`

However, if you would prepare `a` in Montgomery form, you could do this which avoid doing (expensive) modulus operation:
```
if ((err = mp_mul(t2, a, t1)) != CRYPT_OK)                                 { goto done; }
if ((err = mp_montgomery_reduce(12, modulus, mp)) != CRYPT_OK)              { goto done; }
```


You could prepare `a` in `ltc_ecc_mulmod()`. I'm not familiar with the exact code/implementation, but looks like you would need smth like this:
`if ((err = mp_mulmod(a, mu, modulus, ma)) != CRYPT_OK)                   { goto done; }`
Thus you would multiply `a` by `R` modulo `N` as explained in wikipedia:
https://en.wikipedia.org/wiki/Montgomery_modular_multiplication#The_REDC_algorithm

Hope this helps! :)

**Comment by karel-m** [comment]
I have split this my branch `miko-ecc-enhancements` with ECC enhancements to:
* #236 ECC enhancements part 1 (curves y^2 = x^3 + ax + b) - branch `pr/ecc-non-asn1-part`
* #187 ECC enhancements part 2 (ASN.1 changes) - branch `pr/ecc-asn1-part` (based on `pr/ecc-non-asn1-part`)

Therefore I am closing this issue, please move further discussion to #236 + #187
