### ISSUE TITLE
Target "install" in makefile causes modification time to always change

### ISSUE THREAD

**Issue by alexpolt** [libtom/libtomcrypt#340]
### Prerequisites
* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description
Problem with running under CMake: target "install" in makefile causes this command in makefile_include.mk to execute:
    install -m 644 $(HEADERS) $(DESTDIR)$(INCPATH)  
This -m option changes modification time. And as a result, files including "tomcrypt.h" get rebuild.
Fixing is easy by adding -p (preserve modification time): install -pm ....

### Steps to Reproduce
We use the following config under CMake:
ExternalProject_Add(                                                                                                              
    LibTomCrypt                                                                                         
    GIT_REPOSITORY https://github.com/libtom/libtomcrypt                                                
    UPDATE_DISCONNECTED 1                                                                               
    CONFIGURE_COMMAND ""                                                                                
    BUILD_COMMAND cd <SOURCE_DIR> && make -j                                                            
    INSTALL_COMMAND cd <SOURCE_DIR> && make install PREFIX=<INSTALL_DIR>                                
)                                                                                                       

### Version
#define SCRYPT  "1.18.0" 
MacOS Sierra Version 10.12.6, Darwin Kernel Version 16.7.0

**Comment by sjaeckel** [comment]
@stapelberg @andreyv @scaronni I guess the `-p` switch would be okay to add!?

**Comment by sjaeckel** [comment]
Fine like that?

**Comment by alexpolt** [comment]
Sorry, will only be able to check on Monday. I'll write back!

**Comment by alexpolt** [comment]
Checked. Works.
