### ISSUE TITLE
Failed to build with VS 2017

### ISSUE THREAD

**Issue by VerHext** [libtom/libtomcrypt#344]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Steps to Reproduce
Failed to build lib in VisualStudio 2017. If i try to build the lib (latest) in Visual Studio 2017 it failed with lots of Include errors. 

![image](https://user-images.githubusercontent.com/25115243/35646083-53c96a1e-06ce-11e8-9c3b-e94c04e8f2b3.png)

Should i need a other lib to build libtomcrypt? 

### Version

Windows 10 8.0 SDK  Visual Studio 2017

**Comment by rofl0r** [comment]
those are standard C headers. looks like your IDE include path is not properly set up.

**Comment by sjaeckel** [comment]
Unfortunately I don't have a Win10 installation available, but I'll try to install VS2017 on a Win8.1 VM tomorrow.

**Comment by sjaeckel** [comment]
The problem is the selected Windows SDK version that somehow stays at 8.something after the migration of the project.

1. Right-click on the libtomcrypt project -> Settings
2. On top of that new Dialog you can change the settings depending on the configuration, select all configurations there
3. In the First element called "Allgemein" in the German version, most likely "General" in English is an entry "Windows SDK-Version". Change that to the one that is available (10.0.16299.0 in my case).

Also you need to make sure to have libtommath in the same hierarchy as the libtomcrypt folder.

**Comment by VerHext** [comment]
Thank you.
Now i have a smal quesation. I want to calculate the RSA . But I dont find in the lib the right int for the big number any any functions.

my example 
```
x = 5733336211291957930059404707424515459001308671312770355953656564034332742203603124315643680841135124130078998386115460347685517060243789055573316102146724;
n = 12195768979127026417187603714036391958048299327164883087603312522730977833600860696919578595717794043319551957556836036894416267108725971086946438691747253;
int level = 10000;

x ^ (2 ^ level) % n

```
How can i calculate this. I dont find any functions like pow() mod() powMod()... Sory but i'm starter in crypto 😃

**Comment by sjaeckel** [comment]
Well for the basic math you can start to read the documentation and/or book that comes with libtommath, pre-built PDF's are available e.g. [here](https://github.com/libtom/libtommath/releases/tag/v1.0.1).
Also you can read the RSA chapter of the documentation of libtomcrypt, pre-built PDF e.g. [here](https://github.com/libtom/libtomcrypt/releases/tag/v1.18.1).
The last chapter of the ltc doc also gives a glance on the integration of the math library (called MPI provider) within ltc, but that chapter's far from complete.
If you need further help, feel free to post to the ML or open a new issue, but please don't re-use existing issues.
