### ISSUE TITLE
Need help with RSA

### ISSUE THREAD

**Issue by VerHext** [libtom/libtomcrypt#345]
Hello,

now i reading the pdf from libtomaths and libtomcrypt. But i have lots of question if i generate a RSA key.
for my solution is the function (10.5.2) the right. Then i want to generate the RSA from a very big int.
But with the docu i don't know if i use this funktion.
a) my int is to large for the functions (256 length).
c) `rsa_key` is it = null?

My example: 
```

//x= 5733336211291957930059404707424515459001308671312770355953656564034332742203603124315643680841135124130078998386115460347685517060243789055573316102146724
//n = 12195768979127026417187603714036391958048299327164883087603312522730977833600860696919578595717794043319551957556836036894416267108725971086946438691747253
		rsa_make_key(
			12195768979127026417187603714036391958048299327164883087603312522730977833600860696919578595717794043319551957556836036894416267108725971086946438691747253,
			5733336211291957930059404707424515459001308671312770355953656564034332742203603124315643680841135124130078998386115460347685517060243789055573316102146724,
			154,
			10000,
                      null
		);
```
Please give me a example.

**Comment by gahr** [comment]
https://github.com/libtom/libtomcrypt/blob/develop/tests/rsa_test.c#L319

**Comment by sjaeckel** [comment]
if you want to use the parameters separately you can use the combination of `radix_to_bin()`, `rsa_set_key()` and optionally `rsa_set_factors()` and `rsa_set_crt_params()` as shown in https://github.com/libtom/libtomcrypt/blob/develop/tests/rsa_test.c#L248-L255

```
rsa_key key;
const char* n = "12195768979127026417187603714036391958048299327164883087603312522730977833600860696919578595717794043319551957556836036894416267108725971086946438691747253"
unsigned char n_buf[1024];
unsigned long n_len = sizeof(n_buf);
if (radix_to_bin(x, 10, n_buf, &n_len) != CRYPT_OK) exit(-1);
/* do this also for e and d */
...
if(rsa_set_key(n_buf, n_len, e_buf, e_len, d_buf, d_len, &key) != CRYPT_OK) exit(-1);
```

**Comment by VerHext** [comment]
Ok thank you for the example. But the radix_to_bin() function dont't work.
I get the error:

```
Exception error 0x63DA9538 in TSClient-l.exe: 0xC0000005: Access Violation when running at position 0x00000000
```

**Comment by sjaeckel** [comment]
w/o source-code nearly impossible to debug

most likely you forgot to initialize the mpi provider!?

**Comment by VerHext** [comment]
```  initialize the mpi provider ``` I don't read anything in the pdf about the mpi provider. How can I initialize  it?

**Comment by sjaeckel** [comment]
depending on the math library you want to use, you have to set `ltc_mp` to one of `{gmp,ltm,tfm}_desc`

an example is shown in ch. 15.4.3 of the pdf

**Comment by VerHext** [comment]
I have tried almost everything but I can't install the libtommath lib as a mpi provider.

I built and installed the libtonmath and libtoncrypt with make. But he still shows me that the variable ("ltm_desc") is not declared. I added the following code to my make file ..

```make
default: libtommath libtomcrypt

libtommath/%.o: libtommath/%.c
	$(CC) $(CFLAGS) -I./libtommath -o $@ -c $<

libtommath: $(LTM_OBJECTS)

LTC_CFLAGS = $(CFLAGS) -Ilibtomcrypt/src/headers -Ilibtommath -DLTC_SOURCE -DLTM_DESC -o $@

```

Can anyone help me?

**Comment by buggywhip** [comment]
> On 9Apr, 2018, at 10:55 AM, Johannes Waigel <notifications@github.com> wrote:
> 
> LTC_CFLAGS = $(CFLAGS) -Ilibtomcrypt/src/headers -Ilibtommath -DLTC_SOURCE -DLTM_DESC -o $@
> Can anyone help me?
> 
Did you try adding -DUSE_LTM as per the PDF.

...and then somewhere near the top of your pgm, ltc_mp = tfm_desc;

**Comment by sjaeckel** [comment]
That's a pretty incomplete makefile example, feel free to provide a full one and we can probably help you.

> Did you try adding -DUSE_LTM as per the PDF.

Good idea, but if you didn't use the same pattern in your code it won't help, as it's only relevant for the demos.

**Comment by VerHext** [comment]
Thats my make file.

https://pastebin.com/XNg88094

Thank you for the support...

**Comment by sjaeckel** [comment]
where does `LTC_OBJECTS` come from?

**Comment by VerHext** [comment]
```
LTC_OBJECTS = \
libtomcrypt/src/math/ltm_desc.o
```

**Comment by sjaeckel** [comment]
which means that makefile is still incomplete.
have you tried using the default makefile/makefile.shared and simply link your application to the libraries created from there?

**Comment by karel-m** [comment]
Maybe also have a look at my old example https://github.com/karel-m/libtomcrypt-subset

**Comment by buggywhip** [comment]
Going back to basics....  

Are you building your own custom make file?  ...a single file that builds both?  If so, that is not the typical build paradigm for LTM and LTC. 

...and something is not right with your placement of -DUSE_LTM at the bottom of your makefile at pastebin.  

What is it you are trying to do?  

???

Sent fm iTouch

**Comment by VerHext** [comment]
Thank you @karel-m . Now i created my own make file.

```make
PROGRAM = TS3Client
INCLUDEDIRS = \
	-I/usr/local/include

LIBDIRS = \
	-L/usr/local/lib \

LIBS = -Llibtomcrypt -Llibtommath

CXXSOURCES = main.cpp Crypto.cpp Packet.cpp PacketHandler.cpp Util.cpp
CXXOBJECTS = $(CXXSOURCES:.cpp=.o) 
CXXFLAGS = -DESRI_UNIX $(INCLUDEDIRS) -DUSE_LTM -DLTM_DESC
CXX = g++

LDFLAGS = $(LIBDIRS) $(LIBS)

main: $(PROGRAM)

$(PROGRAM): $(CXXOBJECTS) 
	$(CXX) -o $@ $(CXXOBJECTS) $(LDFLAGS)

clean:
	$(RM) -f $(CXXOBJECTS) $(PROGRAM)
```

My libtoncrypt.a and libtommath.a are in the folder /usr/local/lib/
But now i get the error thats `radix_to_bin` and `ltm_desc` are undefined.
I dont understand what is wrong...

**Comment by karel-m** [comment]
Change:

LIBS = -ltomcrypt -ltommath

**Comment by VerHext** [comment]
It fix the `radix_to_bin` error but not the `ltm_desc` undefined error.

**Comment by sjaeckel** [comment]
Simply. Post. Your. Entire. Makefile.

Not just incomplete parts of it.

**Comment by VerHext** [comment]
This is my complete Makefile. How I sent him above ...

**Comment by sjaeckel** [comment]
can you try to add `$(CXXFLAGS)` to your `$(CXX)` invocation for the `$(PROGRAM)` target?

I just took the makefile renamed demos/small.c to small.cpp and adapted it to compile that and this was the only thing that was missing...

```
diff --git a/demos/Makefile b/demos/Makefile
index 6648812..7b6d197 100644
--- a/demos/Makefile
+++ b/demos/Makefile
@@ -1,7 +1,7 @@
-PROGRAM = TS3Client
+PROGRAM = small
 INCLUDEDIRS = \
-       -I/usr/local/include
+       -I../src/headers -I../../libtommath
 
 LIBDIRS = \
-       -L/usr/local/lib \
+       -L.. -L../../libtommath
 
@@ -9,3 +9,3 @@ LIBS = -ltomcrypt -ltommath #changed
 
-CXXSOURCES = main.cpp Crypto.cpp Packet.cpp PacketHandler.cpp Util.cpp
+CXXSOURCES = small.cpp
 CXXOBJECTS = $(CXXSOURCES:.cpp=.o) 
@@ -19,3 +19,3 @@ main: $(PROGRAM)
 $(PROGRAM): $(CXXOBJECTS) 
-       $(CXX) -o $@ $(CXXOBJECTS) $(LDFLAGS)
+       $(CXX) -o $@ $(CXXOBJECTS) $(CXXFLAGS) $(LDFLAGS)
 
diff --git a/demos/small.cpp b/demos/small.cpp
index de1f93d..d494f60 100644
--- a/demos/small.cpp
+++ b/demos/small.cpp
@@ -16,2 +16,3 @@ int main(void)
    register_hash(&sha256_desc);
+   ltc_mp = ltm_desc;
    return 0;
```

```
$ make
g++ -DESRI_UNIX -I../src/headers -I../../libtommath -DUSE_LTM -DLTM_DESC   -c -o small.o small.cpp
g++ -o small small.o  -DESRI_UNIX -I../src/headers -I../../libtommath -DUSE_LTM -DLTM_DESC -L.. -L../../libtommath -ltomcrypt -ltommath
$ ./small 
$ echo $?
0
```

**Comment by VerHext** [comment]
No unfortunately, it doesn't find the variable "ltm desc"

**Comment by VerHext** [comment]
@karel-m if i build my libtomcrypt lib with your parameters, i will get following output:

```
g++ -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC   -c -o main.o main.cpp
g++ -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC   -c -o Crypto.o Crypto.cpp
g++ -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC   -c -o Packet.o Packet.cpp
g++ -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC   -c -o PacketHandler.o PacketHandler.cpp
g++ -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC   -c -o Util.o Util.cpp
g++ -o TS3Client main.o Crypto.o Packet.o PacketHandler.o Util.o   -DESRI_UNIX -I/usr/local/include -DUSE_LTM -DLTM_DESC -L/usr/local/lib  -ltomcrypt -ltommath
cc -L/usr/local/lib  -ltomcrypt -ltommath  main.o TS3Client   -o main
/usr/bin/ld: TS3Client: _ZSt4cout: invalid version 6 (max 0)
TS3Client: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
<built-in>: the rule for target "main" failed
make: *** [main] Error 1

```

**Comment by karel-m** [comment]
You are probably running something else. It should look like:
```
$ git clone https://github.com/libtom/libtomcrypt.git
remote: Counting objects: 16178, done.
remote: Compressing objects: 100% (260/260), done.
remote: Total 16178 (delta 300), reused 365 (delta 235), pack-reused 15681
Receiving objects: 100% (16178/16178), 20.09 MiB | 8.59 MiB/s, done.
Resolving deltas: 100% (12184/12184), done.

$ cd libtomcrypt

$ make CFLAGS="-DLTM_DESC -I/usr/local/include" install
   * gcc src/ciphers/aes/aes.o
   * gcc src/ciphers/anubis.o
   * gcc src/ciphers/blowfish.o
   * gcc src/ciphers/camellia.o
   * gcc src/ciphers/cast5.o
[...]
   * gcc src/stream/sosemanuk/sosemanuk.o
   * gcc src/stream/sosemanuk/sosemanuk_test.o
   * ar libtomcrypt.a
ar: creating libtomcrypt.a
   * ranlib libtomcrypt.a
install -p -d /usr/local/include
install -p -d /usr/local/lib
install -p -m 644 libtomcrypt.a /usr/local/lib/libtomcrypt.a
install -p -m 644 src/headers/tomcrypt.h src/headers/tomcrypt_argchk.h src/headers/tomcrypt_cfg.h
  src/headers/tomcrypt_cipher.h src/headec/headers/tomcrypt_hash.h src/headers/tomcrypt_mac.h
  src/headers/tomcrypt_macros.h src/headers/tomcrypt_math.h src/headers/tomcrypt_misc.pk.h
  src/headers/tomcrypt_pkcs.h src/headers/tomcrypt_prng.h /usr/local/include

$ ls -sh /usr/local/lib/libtomcrypt.a
1.6M /usr/local/lib/libtomcrypt.a
```

**Comment by VerHext** [comment]
yes, creating the lib works fine. 
The error comes from the top, when I want to build my application with make
