### ISSUE TITLE
release needed - soon

### ISSUE THREAD

**Issue by rofl0r** [libtom/libtomcrypt#36]
it's been 3 years since this tomcrypt fork exists, and afaik there hasn't been any release.

i fear that if the development continues at this pace, libtomcrypt will be rendered obsolete soon.

from the outside it looks dead, so new software will probably not be written against it anymore, and chances that security researchers test a library that's not been updated since 4 years are little.

so if you really want to keep this project alive, you better start merging patches into master and pushing out releases soon.

**Comment by justinclift** [comment]
The code seems reasonably stable at present.

Any chance of a 1.18 release with the current code base, if things aren't quite good enough for 2.0.0?

It'd make a positive difference for OSX users. :smile:

**Comment by karel-m** [comment]
I suggest closing this one.

**Comment by rofl0r** [comment]
has there been a release now ? btw i applaud you to the good work done in the last weeks.

**Comment by sjaeckel** [comment]
> has there been a release now ?

that's why I left this issue open, as this was the first issue to mention a missing release and as an 'issue to close' as soon as it has been done

**Comment by justinclift** [comment]
Hmmm, 1.17 (from 2010) is still the latest shown both here in the "Releases" part of the repo, and on the libtom.net website.

Are those the wrong places to be looking? :smile:

**Comment by wheybags** [comment]
*Bump* agreed that a new release is needed soon.
I want to package this for [hunter](https://github.com/ruslo/hunter), and it's a bit of a blocker that the latest release it 7 years and 600 commits behind develop

**Comment by sjaeckel** [comment]
Looks like we'll finally get to that point... Is anyone interested in testing an RC? Resp. does anyone still have some open issues? I will have a look at the Mac build soon, so please keep your issues for Mac until I worked on that :)

**Comment by rofl0r** [comment]
a release candidate would be great. once it's been announced on the web page, surely people will download it soon and start testing.

**Comment by sjaeckel** [comment]
> a release candidate would be great. once it's been announced on the web page, surely people will download it soon and start testing.

here we go https://github.com/libtom/libtomcrypt/releases/tag/v1.18.0-rc1

resp. www.libtom.net

**Comment by sjaeckel** [comment]
I forgot to also mention https://github.com/libtom/libtomcrypt/releases/tag/v1.18.0-rc2 here
sorry

**Comment by apjanke** [comment]
FYI, I'm happy to help testing RCs on Mac once you get there. I'm not a libtomcrypt user, but I'm a Homebrew maintainer and have some experience getting various packages to build and install on Mac, and I know we have some users interested in using libtomcrypt, so I'll pitch in here if it would be useful.

**Comment by karel-m** [comment]
https://github.com/libtom/libtomcrypt/releases/tag/v1.18.0-rc4

**Comment by karel-m** [comment]
https://github.com/libtom/libtomcrypt/releases/tag/v1.18.0-rc5

**Comment by sjaeckel** [comment]
https://github.com/libtom/libtomcrypt/releases/tag/v1.18.0

**Comment by rofl0r** [comment]
congratulations! you guys did a great job!

**Comment by karel-m** [comment]
> This is ground control to Major (lib)Tom
>
> Commencing countdown, engines on
>
> 4 .. 3 .. 2 .. 1 .. RELEASE!

Thank you all for your patience and see you by libtomcrypt-1.19, which should happen, according to our release frequency, no later than 2027.

**Comment by buggywhip** [comment]
Congratulations!  

Karel and Steffen, you did some serious heavy lifting for which we are grateful.  Thank you!

...and 2027?  I dunno, that makes for an awfully tight schedule.


.
