### ISSUE TITLE
The size of shared secret in case of RSA based DH is coming out to be 1 byte less than the size of Prime. 

### ISSUE THREAD

**Issue by hmnsh18** [libtom/libtomcrypt#360]
Dear LibTomCrypt team,

I am observing that the size of shared secret in case of RSA based DH is coming out to be 1 byte less than the size of Prime P. Ideally the size of shared secret should be same as of Prime P. This is always the case on case of RSA encryption and signature generation. This behavior is being observed very rarely and most of time I get the size of shared secret always same as of Prime P. 
Is this an expected behavior?

Regards
Himanshu

**Comment by karel-m** [comment]
Do you have some code demonstrating your problem?

**Comment by hmnsh18** [comment]
Hi Karel,

I don't have nay sample code to demonstrate the problem. First of all, I
would like to know whether this is a problem or not. This scenario can be
replicated by calling the function "dh_generate_key" in a loop. After
calling this function, one should check for the size of generated public
key with the size of Prime P. Ideally it should be equal to Prime P, but
sometimes it comes out to be one byte less than the size of Prime P.

Regards
Himanshu

**Comment by karel-m** [comment]
In theory DH public key can be anything between: `1 < pubkey < prime - 1 `

There is roughly 1:256 chance that the public key will be one byte shorter that the prime.
