### ISSUE TITLE
Re-work OID handling

### ISSUE THREAD

**Issue by sjaeckel** [libtom/libtomcrypt#362]
Follow-up of OID handling of #309

**Comment by karel-m** [comment]
FYI: During my work on a support for encrypted pkcs8 ecc keys the OID stuff became even more complicated see https://github.com/libtom/libtomcrypt/blob/pr/ecc-asn1-part/src/pk/ecc/ecc_import_pkcs8.c

**Comment by karel-m** [comment]
The more I fiddle with OID stuff the more I think that our API (public functions, public structs) shoudl use string representation e.g. `"1.2345.67.8.9.10"`. I see the API breakage of flexi-decoded OID's but I still consider using strings more appropriate.

**Comment by karel-m** [comment]
I would:
* keep `LTC_ASN1_OBJECT_IDENTIFIER` (we use it quite a lot even in libtomcrypt itself)
* introduce `LTC_ASN1_OID_STRING`
* switch  flexi-decode implementation to `LTC_ASN1_OID_STRING`

**Comment by sjaeckel** [comment]
> I would:
> * keep `LTC_ASN1_OBJECT_IDENTIFIER` (we use it quite a lot even in libtomcrypt itself)
> * introduce `LTC_ASN1_OID_STRING`
> * switch  flexi-decode implementation to `LTC_ASN1_OID_STRING`

sounds good!

I'm thinking about defaulting to only decode to `LTC_ASN1_OID_STRING` and if s/o requests a `LTC_ASN1_OBJECT_IDENTIFIER` to convert.
The advantage would be:
* we are relying on one implementation of the decoding
* that implementation/conversion will then finally detect&report potential overflows of subidentifiers

I've also pushed a starting point to the branch [rework/oid](https://github.com/libtom/libtomcrypt/tree/rework/oid) that removes `oid_st`. Should I already open a PR for that?

**Comment by karel-m** [comment]
Yes, I am for opening a new PR so that we see what Travis-CI thinks about the changes.

Ad: _only decode to LTC_ASN1_OID_STRING_  👍
