### ISSUE TITLE
Non-portable branch name causing problems

### ISSUE THREAD

**Issue by mcorino** [libtom/libtomcrypt#409]
Could someone (@buggywhip ?) please rename (or remove) the branch named `remove-sosemanuk_setup()-"NOP"`.
Trying to update the repo on Windows is causing major pains at the moment. Windows doesn't seem to be able to create file names with double quotes in the name.

**Comment by sjaeckel** [comment]
@buggywhip :rofl: 

yeah, I'm going to merge #406 so we can remove the branch
