### ISSUE TITLE
Exportation of ECC Keys

### ISSUE THREAD

**Issue by yuanxun6844** [libtom/libtomcrypt#419]
I have ~~two questions~~ one question related to the exportation of ECC keys:

1. ~~Alternatively, is~~ Is it possible to export (and import) ECC public keys as a bytestring of length 33, as is done by Bitcoin Core and other programs?

https://en.bitcoin.it/wiki/Elliptic_Curve_Digital_Signature_Algorithm

It would seem that someone has brought this matter up before, or a related issue, but I do not understand the final result, whether or not it was implemented:

https://github.com/libtom/libtomcrypt/issues/34

Thanks for your help.

**Comment by karel-m** [comment]
Use the following:
```C
ecc_get_key(buf, &buflen, PK_PUBLIC|PK_COMPRESSED, &key);
```

To load the exported key you need to use the following sequence:
```C
ltc_ecc_curve *cu;
ecc_key pubkey;
ecc_get_curve("SECP256K1", &cu); /* bitcoin curve */
ecc_set_dp(cu, &pubkey);
ecc_set_key(buf, buflen, PK_PUBLIC, &pubkey);
```

**IMPORTANT NOTICE:** the API above is currently only in develop branch (and is expected to be part of libtomcrypt 1.19.x series)

**Comment by karel-m** [comment]
UPDATE: we have renamed some of the functions recently in develop branch, now you should use:

```C
ltc_ecc_curve *cu;
ecc_key pubkey;
ecc_find_curve("SECP256K1", &cu); /* bitcoin curve */
ecc_set_curve(cu, &pubkey);
ecc_set_key(buf, buflen, PK_PUBLIC, &pubkey);
```

Unless you have more questions I will close this issue on 13 July.

**Comment by yuanxun6844** [comment]
Thanks. You have been most helpful.
