### ISSUE TITLE
Question Concerning Key Format

### ISSUE THREAD

**Issue by yuanxun6844** [libtom/libtomcrypt#420]
Why are the public and private keys resulting from ecc_export() of variable length? According to the manual of LibTomCrypt, section 12.3, the length is seemingly fixed. A public key consists of flags, keySize, pubkey.x, and pubkey.y, all of which are of fixed length. A private key consists of flags, keySize, pubkey.x, pubkey.y, and secret.k, all of which are of fixed length. I suspect the answer is probably quite obvious but I have missed it. Sorry for opening a new issue, and thanks.

**Comment by karel-m** [comment]
Please keep in mind that `ecc_export()` is a legacy function (using libtomcrypt proprietary format) that was superseded by `ecc_export_openssl()` which is interoperable with other crypto libraries.

The length of `ecc_export` output is simply a result of ASN.1 encoding which is not guaranteed to have fixed length. 

**IMPORTANT NOTICE:** the function `ecc_export_openssl()` is currently available in `develop` branch only.

**Comment by karel-m** [comment]
Unless you have more questions I will close this issue on 13 July.

**Comment by yuanxun6844** [comment]
Thanks. You have been most helpful.
