### ISSUE TITLE
hmac_init should accept 0-length keys

### ISSUE THREAD

**Issue by eduardsui** [libtom/libtomcrypt#425]
I've noticed that hmac_init doesn't accept 0-length keys. However, 0-length keys seem to be valid (see: test vectors in https://tools.ietf.org/html/rfc5869, where salt is the hmac key). This is useful in TLS 1.3 - it uses hkdf. The fix is fairly simple:

In ``hmac_init``:

Replace LTC_ARGCHK(key  != NULL) with LTC_ARGCHK(((key  != NULL) || (keylen == 0)))
And remove these lines:
```
/* valid key length? */
if (keylen == 0) {
    return CRYPT_INVALID_KEYSIZE;
}
```

After modifying it, RFC5869, A.3.  Test Case 3 is ok.
```
prk (32): 19 EF 24 A3 2C 71 7B 16 7F 33 A9 1D 6F 64 8B DF 96 59 67 76 AF DB 63 77 AC 43 4C 1C 29 3C CB 04
output (42): 8D A4 E7 75 A5 63 C1 8F 71 5F 80 2A 06 3C 5A 31 B8 A1 1F 5C 5E E1 87 9E C3 45 4E 5F 3C 73 8D 2D 9D 20 13 95 FA A4 B6 1A 96 C8
```

**Comment by sjaeckel** [comment]
well https://github.com/libtom/libtomcrypt/blob/develop/src/misc/hkdf/hkdf_test.c#L137 passes so you should probably use the hkdf API instead of the hmac API :)
