### ISSUE TITLE
How to import RSA PKCS#8 public key

### ISSUE THREAD

**Issue by sigusr1** [libtom/libtomcrypt#434]
I generate a public rsa key in format PKCS#8 as follow:

`-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEhUdwtAgFPoOsWFFLflyg7R7z
wRqfDBUouMu1G/LigXHDN4mhfQjiHzn/M/gBYrq7GcI0EmXnBJ1sfsTZmccAkE2r
201ZwbYQKaWh6lCh6Os/Z63DSfGt56dru7HQSvtsNIQ0wLXiEOSuiMF9TNCuQVxc
ibZ7NPDq5/ZYsDqjkQIDAQAB
-----END PUBLIC KEY-----
`

I try follow workflow:
1. Call rsa_import_pkcs8 directly,   fail.
2. First strip "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----", then base64 decode left data, and finally call rsa_import_pkcs8， fail too.

3. First strip "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----", then base64 decode left data, and finally call rsa_import，the return value is 0. Is this right?

**Comment by sjaeckel** [comment]
public keys aren't stored as PKCS#8

`rsa_import()` can be used to import that key.

**Comment by sigusr1** [comment]
Get it, thanks.
