### ISSUE TITLE
byte is going to be part of C++ standard

### ISSUE THREAD

**Issue by mika314** [libtom/libtomcrypt#439]
### Description

byte is going to be part of C++ standard macrodefined byte in the library conflicting with byte from C++ standard.

### Steps to Reproduce

Include ```<cstdint>``` and compile with C++17 flag.

### Version

/* version */
#define CRYPT   0x0118
#define SCRYPT  "1.18.1"

**Comment by karel-m** [comment]
Which of our macros do you mean?

**Comment by mika314** [comment]
https://github.com/libtom/libtomcrypt/blob/c5e4679b7ae0ab09d449567ec287c19db210de5f/src/headers/tomcrypt_macros.h#L433

**Comment by karel-m** [comment]
`byte` macro is used in:
```
src/ciphers/aes/aes.c
src/ciphers/blowfish.c
src/ciphers/cast5.c
src/ciphers/des.c
src/ciphers/twofish/twofish.c
src/hashes/tiger.c
src/mac/pelican/pelican.c
```

Quick hack may be moving it to `tomcrypt_private.h`

Or we can rename it to `LTC_BYTE`

Or both, renaming it to `LTC_BYTE` and moving it to `tomcrypt_private.h`

@sjaeckel ?

**Comment by sjaeckel** [comment]
> Or both, renaming it to `LTC_BYTE` and moving it to `tomcrypt_private.h`

IMO the best

but then we must also discuss if we could live with this kind of API breakage for a potential version 1.18.3 ...

**Comment by karel-m** [comment]
The bunch of ecc_* related API breaking changes (== current develop) will go to 1.19.x or 1.18.3?

**Comment by sjaeckel** [comment]
> The bunch of ecc_* related API breaking changes (== current develop) will go to 1.19.x or 1.18.3?

IMO that's even 2.0.0

[edit]: as 1.18 is still API compatible to 1.17 even though we broke the ABI, but current develop won't be API compatible so we should increase the major version

**Comment by karel-m** [comment]
I would say that 1.19 is enough, but whatever...

In that case LTC_BYTE can go to `develop` branch and be released together with ecc changes.

**Comment by sjaeckel** [comment]
> I would say that 1.19 is enough, but whatever...

if breaking the API isn't reason enough for you to bump the major version number, what is it then?

**Comment by karel-m** [comment]
It depends on how breaking the breakage is. The only thing we broke in ECC is using custom curves; vast majority of ecc_* functions is still backwards incompatible.

A huge change deserving major version bump is IMO for example migration from `unsigned long` to `size_t`.

Anyway, this issue was fixed. Closing.
