### ISSUE TITLE
ssh_decode_sequence_multi & compiler error

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#460]
I have got this report:
```
cc ... -c ltc/misc/ssh/ssh_decode_sequence_multi.c -o ltc/misc/ssh/ssh_decode_sequence_multi.o
{standard input}: Assembler messages:
{standard input}:100: Error: Incorrect register `%rbx' used with `l' suffix
{standard input}:101: Error: Incorrect register `%rbx' used with `l' suffix
*** [ltc/misc/ssh/ssh_decode_sequence_multi.o] Error code 1
```
It is probably: gcc 4.2.1 20070831 patched [FreeBSD]

Full report http://www.cpantesters.org/cpan/report/341fe940-d829-11e8-9067-b381f67cb40a

And ... I have absolutely no idea what's going on.

Cc: @rmw42

**Comment by rmw42** [comment]
Well, since we don't have any assembly language in there, that's gotta be a compiler bug...

**Comment by sjaeckel** [comment]
Could it be related to the invocation of `LOAD {32,64}H()` while dereferencing a pointer? 

That's the only part of the code which pulls in assembly

**Comment by rmw42** [comment]
Ah, hadn't seen that... it's nothing like the error, though:
```
#define LOAD64H(x, y)          \
asm __volatile__ (             \
   "movq (%1),%0\n\t"          \
   "bswapq %0\n\t"             \
   :"=r"(x): "r"(y): "memory");
```

**Comment by rmw42** [comment]
It also successfully compiled `ciphers/camellia.c`, `encauth/gcm/gcm_gf_mult.c` and `hashes/sha2/sha512.c`, which all use `LOAD64H()`, so I can't see it being the inline asm for that macro...

**Comment by rmw42** [comment]
I guess the only way we'll get to the bottom of this is if someone can find a FreeBSD box with that compiler on it. Replacing `-o ltc/misc/ssh/ssh_decode_sequence_multi.o` with `-S -o ssh_decode_sequence_multi.s` in the CC command will get the asm it was generating, and the issue is around line 100...

**Comment by sjaeckel** [comment]
I know that'd be only a temporary solution, but do you even provide an API in Perl for those ssh functions? 
If not, couldn't you simply disable their compilation?

**Comment by karel-m** [comment]
Cc @eserte

Hi Slaven, we are discussing here a compiler error from your cpantester report related to my perl module CryptX. The error is basically a failure to compile one file from libtomcrypt library - see http://www.cpantesters.org/cpan/report/341fe940-d829-11e8-9067-b381f67cb40a

Is the compiler and/or the platform of this cpantester machine somehow unusual/special? Does the same cpantester machine complain/fail in a similar way with other libraries/modules?

**Comment by karel-m** [comment]
> couldn't you simply disable their compilation?

The irony is that we hit here the reverse of #449 which can be called: "ecc_sign_hash_ex + ecc_verify_hash_ex forces linking SSH decode/encode code" 😄 

So maybe after #450 or something like that I can simply exclude `ssh_(en|de)code_sequence_multi.c`

**Comment by eserte** [comment]
I checked on another (real, non-VM) freebsd9 machine, and the same compiler error happens here, too.
What works on both machines is to use the installed gcc 4.8 compiler:
```
perl Makefile.PL CC=gcc48
```

And I never saw this kind of error while compiling other stuff.

**Comment by karel-m** [comment]
Further investigation revealed that the trouble making line is:
```
LOAD32H(size, in);
```
plus the fact that `size` is `unsigned long` but should be `ulong32`.

So it is fixable, not a compiler bug.

**Comment by karel-m** [comment]
@eserte may I ask you for a quick check whether CryptX-0.061_003 doesn't fail anymore?

http://cpan.metacpan.org/authors/id/M/MI/MIK/CryptX-0.061_003.tar.gz

**Comment by karel-m** [comment]
All green - http://fast-matrix.cpantesters.org/?dist=CryptX%200.061_003

Closing.
