### ISSUE TITLE
Hello, we need some help. How to create a makefile.msvc 

### ISSUE THREAD

**Issue by GGeorgEJS** [libtom/libtomcrypt#467]
### Prerequisites

* [ ] Checked the developer manual
* [ ] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [ ] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

[Description of the issue]

### Version

You can get this information from the define `SCRYPT` in `src/include/tomcrypt.h` or your local git repository by running `git describe --always --tags --dirty`. 
Also, please include the compiler, the compiler version, the architecture and (if applicable) the MPI provider, the OS and what version of the OS you're experiencing the issue.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sjaeckel** [comment]
Can you please explain what your problem is?
