### ISSUE TITLE
demo_dynamic.py uses invalid argument

### ISSUE THREAD

**Issue by janisozaur** [libtom/libtomcrypt#469]
https://github.com/libtom/libtomcrypt/blob/d432b13139ced07e309552f2a4893116883d434a/demos/demo_dynamic.py#L256
passes a pointer to a non-pointer argument `counter` https://github.com/libtom/libtomcrypt/blob/d432b13139ced07e309552f2a4893116883d434a/src/stream/chacha/chacha_ivctr32.c#L27 resulting in invalid ciphers

**Comment by sjaeckel** [comment]
https://github.com/libtom/libtomcrypt/commit/241198ec3d5f623ade262266e86de71f694ee89c

fine like that?

ping @buggywhip @janisozaur

**Comment by janisozaur** [comment]
Lgtm
