### ISSUE TITLE
tomcrypt.h not found (instant contiki)

### ISSUE THREAD

**Issue by matesio** [libtom/libtomcrypt#471]
Hello, do not know if this is the right place to post.
I am trying do some simulations on cooja, i have used libtomcrypt.

I have

instant contiki on virtual box
installed libtomcrypt-dev (installed from src)
-> libtomcrypt.a (usr/lib)
-> libtomcrypt.so (/usr/lib/i386-linux-gnu/)
but it is giving me error (tomcrypt.h not found), but i have *.h in my /usr/include path which is default for gcc as far as i know.

-- myfile.c is working fine with TARGET=native but when i change it to SKY, it comes up with exceptions.

make TARGET=sky savetarget (saving MakeFile.target), seems it is working.
make myfile.upload (generates error tomcrypt.h not found).

**Comment by rofl0r** [comment]
your problem is related to the Makefile you're using, not libtomcrypt... maybe you start by learning how to use the compiler directly...

**Comment by matesio** [comment]
yeah i know, Sorry for posting on wrong place. i have tried to use -ltomcrypt and -L, but no luck, please guide me a little how can i add this in my make file.

**Comment by buggywhip** [comment]
> On 11Dec, 2018, at 9:43 AM, Hammad <notifications@github.com> wrote:
> please guide me a little how can i add this in my make file.
> 
I use...

sudo make -j5 -f makefile.shared  CFLAGS="-DUSE_LTM -DLTM_DESC -DTFM_DESC -DGMP_DESC"  EXTRALIBS="-L/usr/local/lib -ltommath -ltfm -lgmp"  all

YMMV.

**Comment by matesio** [comment]
@buggywhip Thank you So, if want to mention that in my make file, then  it should look like this ?
all: MyFile
```

APPS=servreg-hack
CONTIKI=../../..
CONTIKI_WITH_IPV6 = 1
CFLAGS="-DUSE_LTM -DLTM_DESC -DTFM_DESC -DGMP_DESC"
EXTRALIBS="-L/usr/local/lib -ltommath -ltfm -lgmp"  all
include $(CONTIKI)/Makefile.include
```

**Comment by karel-m** [comment]
try
```
CFLAGS="-DUSE_LTM -DLTM_DESC -DTFM_DESC -DGMP_DESC -I/usr/local/include"
```

**Comment by matesio** [comment]
**MakeFile**

```
all: test
APPS=servreg-hack
CONTIKI=../../..

CONTIKI_WITH_IPV6 = 1
CFLAGS="-DUSE_LTM -DLTM_DESC -DTFM_DESC -DGMP_DESC -I/usr/local/include"

include $(CONTIKI)/Makefile.include


```
But when i execute 'make test.sky TARGET=sky' it gives same error, **tomcrypt.h** not found
@karel-m

**Comment by buggywhip** [comment]
> On 12Dec, 2018, at 1:09 AM, Hammad <notifications@github.com> wrote:
> 
> it gives same error, tomcrypt.h not found

what do you get when you do:  sudo find / -name tomcrypt.h

...and are you including that path?

**Comment by matesio** [comment]
It is in. /usr/local/include/tomcrypt.h

**Comment by buggywhip** [comment]
I am not expert in the construction of makefiles, so with a grain of salt...  I get the impression the problem lies with the makefile itself.  ...perhaps trying to do too much at once.

Try building your LTC library separately (use a variant of my command), then linking the lib into your app.

???

**Comment by matesio** [comment]
I did build library too with your command, but still no success. I am just wondering why it is not accessing all *.h in my path, /usr/local/include.

**Comment by buggywhip** [comment]
what about permissions on tomcrypt.h?

**Comment by matesio** [comment]
-rw-r--r-- 1 root root 2957 Nov 29 17:49 /usr/local/include/tomcrypt.h

**Comment by buggywhip** [comment]
with another grain of salt...

makefiles usually have conditions followed with indented actions, and the commands must be indented with tabs.  I didn't see any.  does this apply here?

**Comment by matesio** [comment]
That should throw an error. I believe  i have to do something with my gcc paths to include headers to linux environment, but unable to figure out how to achieve this. I have opened same issue on contiki repo (**[https://github.com/contiki-os/contiki/issues/2541]**) about 2 weeks ago but got no response, I decided to post here, is making me desperate and I am waiting for time when it will be executed in success.

**Comment by buggywhip** [comment]
perhaps you can find other contiki app projects that have makefiles that you can use as a model?

**Comment by sjaeckel** [comment]
which contiki version?

**Comment by matesio** [comment]
latest one, clone from github

**Comment by sjaeckel** [comment]
and instant-contiki version?

**Comment by buggywhip** [comment]
the only other thing I can suggest is to set aside the makefile approach and construct a single gcc command that compiles your app with the include path and links your compiled lib.  

after that works you might try again with a makefile.

**Comment by matesio** [comment]
@sjaeckel  don't know exact version, but it is the latest one from github  [https://github.com/contiki-os/contiki]

**Comment by rofl0r** [comment]
that's not how one approaches a compiling issue.
you need to figure out if your compiler is properly configured by compiling a test file **by hand** like:
foo.c:
```
#include <tomcrypt.h>
int main() {}
```

`gcc foo.c`

if that works, your toolchain is OK.
the next thing to debug would be to look at the exact compiler command the makefile uses to compile your program.

**Comment by matesio** [comment]
Thanks, it worked

**Comment by iammrgenie** [comment]
Hello, 

I am having a similar issue and I would like some guidance. I installed the library using the native linux command, sudo apt-get install libtomcrypt-dev.

I found the header file in /usr/local/lib folder. When i use the "#include tomcrypt.h" it says cant find it. Kindly assist. I am new to this so any guidance would be welcomed.

**Comment by Nour-kb** [comment]
Hello, I have the same problem please i need your help , how can i solve this problem ??
