### ISSUE TITLE
#ifdef/#endif missing

### ISSUE THREAD

**Issue by mjfh** [libtom/libtomcrypt#472]
Thanks for providing libTom. In order to strip it down, I needed an additonal #ifdef/#endif  clause for compiling - seems like it was overlooked. Currently my unit tests pull in ecc_test() and sha256_test() successfully.
Jordan

### Prerequisites

I use a custom configuration not enabling <em>LTC_RNG_GET_BYTES</em>.

### Description

Compiling the source <em>padding_pad.c</em> will fail unless <em>LTC_RNG_GET_BYTES</em> is enabled.

### Steps to Reproduce

Apply attached custom configuration patch only on <em>tomcrypt_custom.h</em> only and compile with <em>make CFLAGS='-DLTC_JORDAN_DEBUG ...' ...</em>

### Suggested Steps to Fix

Apply  attached custom configuration patch to <em>padding_pad.c</em>.

### Version

1.18.2-develop (check-in from 07/11/2018)

[0001-enable-fortuna-sha256-ecc-debugging.patch.txt](https://github.com/libtom/libtomcrypt/files/2685895/0001-enable-fortuna-sha256-ecc-debugging.patch.txt)

**Comment by sjaeckel** [comment]
fixed via #473
