### ISSUE TITLE
In case ARGTYPE=3; the register functions do not work

### ISSUE THREAD

**Issue by danzadok** [libtom/libtomcrypt#474]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

[Description of the issue]

### Version

You can get this information from the define `SCRYPT` in `src/include/tomcrypt.h` or your local git repository by running `git describe --always --tags --dirty`. 
Also, please include the compiler, the compiler version, the architecture and (if applicable) the MPI provider, the OS and what version of the OS you're experiencing the issue.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by danzadok** [comment]
This is a macro definition error

**Comment by sjaeckel** [comment]
1. can you please write proper bug reports and not just an issue line? those templates exist for a reason.
1. `ARGTYPE=3` is a very bad idea
1. I've created a [fix/474 branch](https://github.com/libtom/libtomcrypt/tree/fix/474) which should fix the issue when `ARGTYPE=3`
1. there seems to be a regression somewhere in either ECC (ping @karel-m) or the updated prime checking in libtommath (ping @czurnieden)! currently the latest libtommath can't be used to run the ltc ECC tests!

**Comment by karel-m** [comment]
I confirm that with current libtommath/develop the `ecc_tests` and `dh_test` are failing

**Comment by karel-m** [comment]
libtommath's `mp_prime_is_prime` considers the following prime as a non-prime

```
15525180923007089351309181312584817556313340494345143132023511949029662399491021
07258669453876591642442910007680288864229150803718918046342632727613031282983744
380820890196288509170691316593175367469551763119843371637221007210577919

FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22
514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6
F44C42E9A63A3620FFFFFFFFFFFFFFFF
```

**Comment by czurnieden** [comment]
@karel-m libtommath has been compiled how exactly for that test?

There are a bunch of `define`s to include/exclude algorithms. the default is M-R with bases 2 and 3, `mp_prime_strong_lucas_selfridge` and at least one M-R test with a random base.

The API changed for `mp_prime_is_prime`, too, although it should be down-compatible,  so how did you call it?

I have no problem with the `develop` branch in my fork (v1.0.1-181-g48c95f2), where that prime (it is a certified prime, just if somebody asks) gets detected as a prime when checked with `testme.sh` (actually the whole bunch of tests from `.travis.yml` ). `mp_prime_is_prime` has been called for that  prime with `t = 8`, that means M-R with bases 2,3, strong-lucas, and 8 M-R tests with random bases.

Great.
And I was already thinking: "Oh, that get's a bit too smoothly, doesn't it?"
\*grrr\*
\*sigh\*

**Comment by sjaeckel** [comment]
#476 should've fixed this... and some more :)
