### ISSUE TITLE
cipher_hash_test sha3 missing ifdef

### ISSUE THREAD

**Issue by dlegaultbbry** [libtom/libtomcrypt#478]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

The shake test in cipher_hash_test is missing an ifdef LTC_SHA3

### Steps to Reproduce

Build without LTC_SHA3 and the test will fail to build because of the missing shake functions.

### Version

1.18.2

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sjaeckel** [comment]
Thanks for reporting

This was already fixed in #356
