### ISSUE TITLE
build error libtomcrypt and libtommath in my project

### ISSUE THREAD

**Issue by kakaducsy** [libtom/libtomcrypt#494]
Hi all, 
my project uses both libtomcrypt and libtommath, 
I use default project and build 2 libraries ( libtomcrypt.lib and libtommath.lib), but when integrating to my project, I get some error "redefinition" because of in "tomcrypt.h" use libtommath, 
Please help me to resolve this problem.
Thanks all.

**Comment by sjaeckel** [comment]
Can you please give more details about the issue? Such as the compiler used, the architecture to build for and building on and the version of the library.

**Comment by sjaeckel** [comment]
Please re-open if you have further questions/comments.
