### ISSUE TITLE
Redesign of ed25519 key loading functions

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#502]
Currently we have:
```C
int ed25519_set_key(sk, sklen, pk, pklen, &key);
int ed25519_import(in, inlen, &key);
int ed25519_import_x509(in, inlen, &key);
int ed25519_import_pkcs8(in, inlen, pwd, pwdlen, &dkey);
```

First, I propose replacing `ed25519_set_key` with:
```c
int ed25519_import_raw(in, inlen, type, &key);
/* where type is PK_PRIVATE or PK_PUBLIC */
```

Next, I would suggest renaming `ed25519_import` to `ed25519_import_openssl` and extending it so that it can import not only public keys but also private keys produced by openssl (which is similar to what we do in `ecc_import_openssl`).

The test vectors can be generated by:
```
openssl genpkey -algorithm Ed25519 -out ed25519_sk.pem
openssl pkey -in ed25519_sk.pem -inform PEM -out ed25519_sk.der -outform DER
openssl pkey -in ed25519_sk.pem -inform PEM -out ed25519_pk.der -pubout -outform DER
```

Our `ed25519_import_openssl` should be able to handle both `ed25519_pk.der` and `ed25519_sk.der`.

I am currently short of time for coding therefore opening just an issue,

**Comment by sjaeckel** [comment]
I guess this all applies equally to x25519, right?

> First, I propose replacing `ed25519_set_key` with:
> 
> ```c
> int ed25519_import_raw(in, inlen, type, &key);
> ```

fine by me, what's the expected format of a private key then? 32 bytes of SK only or 64 bytes of PK+SK or shall both be supported?

> The test vectors can be generated by: ...

these two formats you mention are already supported.

> Next, I would suggest renaming `ed25519_import` to `ed25519_import_openssl` and extending it so that it can import not only public keys but also private keys produced by openssl (which is similar to what we do in `ecc_import_openssl`).
> ...
> Our `ed25519_import_openssl` should be able to handle both `ed25519_pk.der` and `ed25519_sk.der`.

you mean `ed25519_import_openssl()` should additionally call `ed25519_import_pkcs8()`?

**Comment by karel-m** [comment]
> what's the expected format of a private key then? 32 bytes of SK only or 64 bytes of PK+SK or shall both be supported?

I had in mind "32 bytes of SK only" 

> you mean ed25519_import_openssl() should additionally call ed25519_import_pkcs8()?

No, let us keep `ed25519_import_pkcs8` separate.
