### ISSUE TITLE
Broken ror

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#513]
Probably by #499 we have managed to break libtomcrypt on couple of compilers/platforms.

See:
* https://github.com/DCIT/perl-CryptX/issues/57
* (FreeBSD/32bit) http://www.cpantesters.org/cpan/report/ae213a7a-f2e8-11e9-9066-e374b0ba08e8
* (Mingw/32bit) http://www.cpantesters.org/cpan/report/69d1d425-6c5d-1014-9482-32a54c72b00b

I am sorry for not testing #499 on exotic platforms/compilers before approving.

**Comment by sjaeckel** [comment]
> I am sorry for not testing #499 on exotic platforms/compilers before approving.

@newbluemoon thx for reporting & fixing!

**Comment by newbluemoon** [comment]
@sjaeckel, @karel-m you’re welcome and thank you for the quick response! :)
