### ISSUE TITLE
Can you tell me where is the definition of function rijndael_ecb_encrypt()

### ISSUE THREAD

**Issue by JadenLiu0103** [libtom/libtomcrypt#519]
### Prerequisites

* [ ] Checked the developer manual
* [ ] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [ ] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

[Description of the issue]

### Version

You can get this information from the define `SCRYPT` in `src/include/tomcrypt.h` or your local git repository by running `git describe --always --tags --dirty`. 
Also, please include the compiler, the compiler version, the architecture and (if applicable) the MPI provider, the OS and what version of the OS you're experiencing the issue.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sjaeckel** [comment]
```sh
$ grep -r rijndael_ecb_encrypt 
...
src/ciphers/aes/aes.c:#define ECB_ENC  rijndael_ecb_encrypt
...
```

**Comment by JadenLiu0103** [comment]
I use gcc to compile and generate the libtomcrypt.a successfully.

Then I use gcc to compile another c file in which rijndael_ecb_encrypt() function is used, error reports that rijndael_ecb_encrypt() is undefined. 
Can you help me about this?

**Comment by JadenLiu0103** [comment]
Sorry, now it works, I install the libtom to the default include and lib folder, and it works now.
Thank you.
