### ISSUE TITLE
finely configure number of array entries  for cipher_descriptor, hash_descriptor, and prng_descriptor

### ISSUE THREAD

**Issue by metalalive** [libtom/libtomcrypt#522]
Hi, I am integrating this cryptography library to my application running on microcontroller-based embedded device. I found that the array `cipher_descriptor`, `hash_descriptor`, and `prng_descriptor` are  declared with  the same  parameter `TAB_SIZE`, which indicates the number of  entries that would be used in the array . 

I am considering to declare these descriptors with different number of entries, (e.g. only 1 entry in prng_descriptor , and 2 entries in hash_descriptor) in order to save some memory space in my case,

I know that I can do this by simply forking this repository and modifying code by myself , but I still would like to ask if there is any plan from you to provide more parameters to finely configure these descriptors ? Thanks for reading.

**Comment by sjaeckel** [comment]
Sorry for the delay.

I think we should first find out if we keep the registry as is or if we follow #515 and remove all registries. In case we keep it, this change would be nice IMO.

As @karel-m already pointed out, #515 and whatever follows in that direction would be a heavily breaking change, but I'm pretty sure it would improve the API's.
