### ISSUE TITLE
building tomcrypt in Visual Studio 2017

### ISSUE THREAD

**Issue by mupchurch-verys** [libtom/libtomcrypt#525]
When I tried to open and build the MS Visual Studio solution (included solution & project), conversion was fine but when I compile it errors out at:

ltm_desc.c(15): fatal error C1083: Cannot open include file: 'tommath.h': No such file or directory

Lo and behold there is no tommath.h file...

**Comment by sjaeckel** [comment]
The VS Solution has per default libtommath as math library enabled to be able to do public key cryptography (RSA, DSA, ECC).

If you don't need public key (PK) cryptography, but only ciphers, hashes etc. you can remove the "LTM_DESC" define from your solution.

In case you want PK crypto please clone https://github.com/libtom/libtommath on the master branch via `git clone https://github.com/libtom/libtommath.git -b master` to the same hierarchy where the libtomcrypt folder is located and build that one first. Then you should be able to build libtomcrypt as well and run the tests.

**Comment by karel-m** [comment]
You need to have source codes of both libtomcrypt and libtommath in directories like:
* `c:\devel\libtomcrypt\`
* `c:\devel\libtommath\`

Than `c:\devel\libtomcrypt\libtomcrypt_VS2008.sln` will be able to "find" `..\libtommath\tommath.h`

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
