### ISSUE TITLE
Building in Debug: Impossible constraint

### ISSUE THREAD

**Issue by DapperDeer** [libtom/libtomcrypt#528]
### Description

Hi, I couldn't find any issue related to the one I'm having and was advised that I should just report this as a bug.

I'm trying to build the library in debug mode using CFLAGS="-g -O0" and although the `./configure` goes well, trying to `make` results in a compilation error for `tomcrypt_macros.h:267: impossible constraint in 'asm'. `

If I've just done something wrong, please let me know, I'm very new to this.

### Steps to Reproduce

It should be noted that I'm trying to use this library with GRUB2, so maybe that's why this is happening. But either way, the steps are pretty simple:

1. Invoke ./configure with CFLAGS="-g -O0"
2. Invoke make

### Version

SCRYPT = 1.16
Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
OS: Ubuntu 18.04

**Comment by sjaeckel** [comment]
Hi,

1. Why do you use version 1.16 of the library?
2. How did you call `configure`? There isn't and there never was autoconf for the library.

You only have to call `make` to build the library.

If you use one of the later versions you can do `make LTC_DEBUG=1` if you want a debug build of the library. For versions <= 1.17 you need to do `CFLAGS="-g -O0" make IGNORE_SPEED=1`

HTH
Steffen

**Comment by DapperDeer** [comment]
1. The code that I'm working on had TomCrypt already installed and I hadn't updated it. Truthfully it hadn't ever crossed my mind!
2. I'm working on a small extension for GRUB and included TomCrypt/TomMath in the makefile/configure files. 

I'll go ahead and update to the latest versions. Do you know if I should build the library using `make LTC_DEBUG=1` and then once added to GRUB, just use regular `make`?

Thanks so much.

**Comment by sjaeckel** [comment]
> I'll go ahead and update to the latest versions. Do you know if I should build the library using `make LTC_DEBUG=1` and then once added to GRUB, just use regular `make`?

Yep, don't use debug builds in production code.

I'm closing this issue.
Please re-open if you have further questions/comments to this issue or open another issue if you have another problem.
