### ISSUE TITLE
AES-CCM encryption allows illegal nonce sizes (violation of Wycheproof tests)

### ISSUE THREAD

**Issue by guidovranken** [libtom/libtomcrypt#536]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

AES-CCM encryption succeeds with IV sizes that are disallowed per Wycheproof: https://github.com/google/wycheproof/blob/4672ff74d68766e7785c2cac4c597effccef2c5c/testvectors/aes_ccm_test.json#L11

### Steps to Reproduce

```c
#include <tomcrypt.h>
#include <stdint.h>

#define CF_CHECK_EQ(expr, res) if ( (expr) != (res) ) { goto end; }
#define CF_CHECK_NE(expr, res) if ( (expr) == (res) ) { goto end; }

int main(void)
{
    uint8_t cleartext[16] = { 0 };
    uint8_t key[16] = { 0 };
    uint8_t iv[1] = { 0 }; 
    uint8_t ciphertext[16];
    uint8_t tag[16];

    unsigned long tag_len = 8;

    if ( register_all_ciphers() == -1) abort();

    CF_CHECK_EQ(ccm_memory(
                find_cipher("aes"),
                key,
                sizeof(key),
                NULL,
                iv,
                sizeof(iv),
                NULL,
                0,
                cleartext,
                sizeof(cleartext),
                ciphertext,
                tag,
                &tag_len,
                CCM_ENCRYPT), CRYPT_OK);

    printf("AES-CCM encryption succeeded with iv size %zu\n", sizeof(iv));

end:

    return 0;
} 
```

### Version

Github recent master branch checkout.

**Comment by sjaeckel** [comment]
> * Checked that your issue isn't already filed: [https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt](https://github.com/issues?utf8=%E2%9C%93&q=repo%3Alibtom%2Flibtomcrypt)

this was solved in #452 

yes it's not in master as there was no release yet that includes this PR

**Comment by guidovranken** [comment]
OK. Apologies for missing the reference to it.

**Comment by sjaeckel** [comment]
No worries :-)
Have a nice weekend!

**Comment by guidovranken** [comment]
Thanks, you too :).
