### ISSUE TITLE
Wishlist: Encryption for ed25519/X25519

### ISSUE THREAD

**Issue by FGasper** [libtom/libtomcrypt#547]
It would be useful to be able to encrypt a string via ed25519/X25519. Could libtomcrypt’s ECDSA encryption algorithm apply also to ed25519/X25519?

Thank you!

**Comment by sjaeckel** [comment]
The version from the develop branch provides this feature.

**Comment by karel-m** [comment]
@sjaeckel I am afraid @FGasper meant `ec25519` analogy to ECDH-based Encrypt and Decrypt as described here  https://github.com/libtom/libtomcrypt/blob/develop/doc/crypt.tex#L5666 = `ecc_encrypt_key` + `ecc_decrypt_key`.

May be we should consider something like https://libsodium.gitbook.io/doc/public-key_cryptography/authenticated_encryption

**Comment by sjaeckel** [comment]
I'm not sure, so let's wait for @FGasper's opinion
