### ISSUE TITLE
Missing tests in test.c

### ISSUE THREAD

**Issue by dlegaultbbry** [libtom/libtomcrypt#548]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

There's a bunch of tests which are not included in test.c, should they all be listed there?

### Steps to Reproduce

N/A

### Version

1.18.2

### Additional Information

https://github.com/libtom/libtomcrypt/blob/develop/tests/test.c#L16

**Comment by sjaeckel** [comment]
What exactly do you mean?

**Comment by dlegaultbbry** [comment]
Well for example, the base64_test doesn't appear in the list so it doesn't run even if you have base64 enabled.

**Comment by sjaeckel** [comment]
`base64_test()` is executed through `misc_test()` from `tests/misc_test.c`
