### ISSUE TITLE
Unpaired #endif

### ISSUE THREAD

**Issue by Alexpux** [libtom/libtomcrypt#572]
Here is unpaired **#endif** in header:
https://github.com/libtom/libtomcrypt/blob/develop/src/headers/tomcrypt_custom.h#L700

**Comment by friedrichsenm** [comment]
It looks like it might be paired with the `#ifndef TOMCRYPT_CUSTOM_H_` right at the top of the file. Maybe there's a reason it's not at the bottom of the file?
