### ISSUE TITLE
Add packages libtomcrypt-dev (and libtommath-dev) ?

### ISSUE THREAD

**Issue by Antoine-aoue** [libtom/libtomcrypt#573]
### Prerequisites

* [X] Checked the developer manual
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [X] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

Like a lot of libraries, there is a package with the suffix `-dev` who includes the header files but for libtomcrypt and libtommath they doesn't exists

### Steps to Reproduce

On archlinux, install `libtomcrypt` package for example.
The headers are not included.

### Version

`v1.18.2-636-g673f5ce2`

**Comment by sjaeckel** [comment]
1. This is not the job of the library maintainers but of the package maintainers of the distro.
2. The arch version seems fine. Go to https://archlinux.org/packages/extra/x86_64/libtomcrypt/ click on `View the file list for libtomcrypt` in the section `Package Contents`

did I miss something?

**Comment by xavierba** [comment]
Actually, the Arch packaging is likely not correct, as it is including the development headers in the main package, while they should be in a libtomcrypt-dev (or libtomcrypt-devel in some distros) sub-package. I have no specific Arch knowledge, but this is how it's done in other distros. So yes, this is a bug, but this is an Arch bug, not a libtomcrypt bug.

**Comment by sjaeckel** [comment]
> Actually, the Arch packaging is likely not correct

![opinion](https://user-images.githubusercontent.com/294374/142870461-4390fec1-21ce-45ee-a06a-3b175ef3bbb9.jpeg)

;)

There are no separate development packages in arch. Sometimes they are split up into `<project>` and `<project>-headers`, but that's only done for huge/complex packages.

**Comment by xavierba** [comment]
I stand corrected. My lack of knowledge about Arch has now been fully demonstrated ;-)

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
