### ISSUE TITLE
Endianness not detected for ARM UWP build

### ISSUE THREAD

**Issue by mabuchner** [libtom/libtomcrypt#576]
Building libtomcrypt for Windows ARM (UWP) using Visual Studio 2019 fails with the following error

> Cannot detect endianness

emitted from

https://github.com/libtom/libtomcrypt/blob/v1.18.2/src/headers/tomcrypt_cfg.h#L191

**Comment by mabuchner** [comment]
[This](https://sourceforge.net/p/predef/wiki/Architectures/) website is helpful for finding appropriate preprocessor defines for detecting the CPU architecture.

**Comment by mabuchner** [comment]
[Here](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160) Microsoft lists their preprocessor defines.

`_M_ARM` and `_M_ARM64` look like good candidates for detecting 32-bit and 64-bit ARM.

**Comment by mabuchner** [comment]
I've added this block of code to `tomcrypt_cfg.h`

```c
/* detect ARM 32-bit */
#if defined(_M_ARM)
   #define ENDIAN_LITTLE
   #define ENDIAN_32BITWORD
#endif

/* detect ARM 64-bit */
#if defined(_M_ARM64)
   #define ENDIAN_LITTLE
   #define ENDIAN_64BITWORD
#endif
```

and now the error is gone.

**Comment by sjaeckel** [comment]
Can you please check whether #626 correctly fixes this?

**Comment by mabuchner** [comment]
Sorry, but I can't really test it anymore. Unfortunately, I had to find a new employer. Now I have neither access to my ex-employers codebase nor a Windows system.

I don't know, if `LTC_FAST` should also be defined for ARM. Apart from that the change **looks** fine to me.

Thanks for taking the time to fix this issue. I'm sure it will benefit other developers.
