### ISSUE TITLE
src of unsigned_read should be const

### ISSUE THREAD

**Issue by mabuchner** [libtom/libtomcrypt#581]
The `ltc_math_descriptor.unsigned_read` function pointer has a non-const `src` pointer argument, which the function is not supposed to modify

https://github.com/libtom/libtomcrypt/blob/673f5ce29015a9bba3c96792920a10601b5b0718/src/headers/tomcrypt_math.h#L179

This is error prone as one might accidentally swap dst and src.

The src pointer should get marked as `const`.

```c
int (*unsigned_read)(void *dst,
                     const unsigned char *src,
                     unsigned long  len);
```

**Comment by mabuchner** [comment]
In various places libtomcrypt tries to use a constant `src`, but it then has to cast away the constness in order to call the `unsigned_read` function. E.g. see this

https://github.com/libtom/libtomcrypt/blob/673f5ce29015a9bba3c96792920a10601b5b0718/src/pk/ecc/ecc_verify_hash.c#L78

**Comment by levitte** [comment]
tomcrypt_math.h lacks const in quite a number of places.  I supposed this is driven by tomsfastmath, which is also seriously lacking in similar cases (although interestingly enough, `fp_read_unsigned_bin` is properly constified, so there's really no excuse for `unsigned_bin`...

**Comment by levitte** [comment]
#654 should fix this particular issue, but not the broader issue of lack of const in ltc_math_descriptor.  That's a more massive piece of work, also involving changes in tomsfastmath.

**Comment by levitte** [comment]
Things have evolved to become a full constification effort, in #667
