### ISSUE TITLE
Compile error if LTC_DER is defined but not LTC_RSA

### ISSUE THREAD

**Issue by J-Richter** [libtom/libtomcrypt#59]
Defining LTC_DER but not LTC_RSA will lead to this compile error:

src/pk/asn1/der/sequence/der_decode_subject_public_key_info.c: In function 'der_decode_subject_public_key_info':
src/pk/asn1/der/sequence/der_decode_subject_public_key_info.c:57:24: error: 'MAX_RSA_SIZE' undeclared (first use in this function)
    tmpbuf = XCALLOC(1, MAX_RSA_SIZE*8);

**Comment by J-Richter** [comment]
I meant LTC_MRSA

**Comment by sjaeckel** [comment]
that's possible, I'll have a look into it after my holidday
