### ISSUE TITLE
Format of r in poly1305?

### ISSUE THREAD

**Issue by donaastor** [libtom/libtomcrypt#617]
I would like to know how is $r$ from Poly1305 represented in the `poly1305_state` structure? It is stored in 5 `uint32`'s: `r[0]`, `r[1]`, `r[2]`, `r[3]`, `r[4]`, but what is the format? Is it a little-endian in some base? Perhaps in the base of `0x3ffffff`? Does it mean that `r[0]` is the value of `r` mod `0x3ffffff`?

The main reason for this is to be able to check if $r$ is too small in which case I want to choose another one.

**Comment by levitte** [comment]
Here's a code in `poly1305_init()` that loads the state from the input *key*:

https://github.com/libtom/libtomcrypt/blob/2302a3a89752b317d59e9cdb67d2d4eb9b53be8e/src/mac/poly1305/poly1305.c#L89-L94

LOAD32L() loads a 32-bit value from an octet string in a little-endian fashion.

Does that answer your questions?
