### ISSUE TITLE
3 Warnings 'Implicit conversion loses integer precision' in tweetnacl.c

### ISSUE THREAD

**Issue by NickBrighten** [libtom/libtomcrypt#618]
Implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' line 184, 185, 204, 205 (from sel25519)

Implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'unsigned long' line 233

Implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') in line 474

**Comment by sjaeckel** [comment]
What do you want to tell me?

I don't see any compiler warnings in our CI builds and if you choose to use different compiler flags than in the example Makefiles etc. you can either choose to provide a PR which fixes them or please keep them for yourself.

Also opening 3 tickets in this style is abusive of the system and bad behavior and you should think whether that's really how you want to behave.
