### ISSUE TITLE
RSA public key decrypt failed 

### ISSUE THREAD

**Issue by badnoodle** [libtom/libtomcrypt#62]
I just change the rsa_test.c:

len2 = sizeof(tmp);
 DO(rsa_export(tmp, &len2, PK_PRIVATE, &key));
 DO(rsa_import(tmp, len2, &pk));
  len2 = sizeof(tmp);
   DO(rsa_export(tmp, &len2, PK_PUBLIC, &key));
  DO(rsa_import(tmp, len2, &sk));

encrypt use private key: 
DO(rsa_encrypt_key(in, rsa_msgsize, out, &len, NULL, 0, &yarrow_prng, prng_idx, hash_idx, &pk));

decrypt use public key:
DO(rsa_decrypt_key(out, len, tmp, &len2, NULL, 0, hash_idx, &stat, &key));

then the test failed, and promot is: A private PK key is required.

does anyone help me ?

**Comment by sjaeckel** [comment]
Invalid

as mentioned in IRC:
```
10:18 < jaeckel> badnoodle: you should probably read https://en.wikipedia.org/wiki/Public-key_cryptography
```
