### ISSUE TITLE
Custom LIBPATH is not reflected in libtomcrypt.pc

### ISSUE THREAD

**Issue by levitte** [libtom/libtomcrypt#625]
This was discovered by looking at Debian's package, where they create an installation like this:

> `$(MAKE) DESTDIR=$(CURDIR)/debian/tmp INSTALL_GROUP=root LIBPATH=/usr/lib/$(DEB_HOST_MULTIARCH) PREFIX=/usr install -f makefile.share`

In my case, `DEB_HOST_MULTIARCH` = x86_64-linux-gnu, which makes complete sense with regards to Debian policies.  However, because `libtomcrypt.pc.in` has a hard coded `libdir=${exec_prefix}/lib`, the resulting system pkg-config (`/usr/lib/x86_64-linux-gnu/pkgconfig/libtommath.pc`) isn't useful.

**Comment by sjaeckel** [comment]
Can you please check whether this fixes the issue for you?

**Comment by sjaeckel** [comment]
Ping @levitte

**Comment by levitte** [comment]
I'm not in a position to actually test it, but from just eyeballing, it looks right to me. I can do tests next week.
