### ISSUE TITLE
Signature verification of X509 certificate

### ISSUE THREAD

**Issue by Larsjep** [libtom/libtomcrypt#634]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't due to the fact that you're using asymmetric cryptography and you forgot linking in and/or setting an MPI provider (usually this causes either random crashes or runtime errors like `LTC_ARGCHK 'ltc_mp.name != NULL' failure ...`). c.f. Ch. "Math Descriptors" of the developer manual.
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

Hi,

I'm trying to verify the signature of a X509 certifcate.

But in order to do that I need the raw data of the tbsCertifcate parts of the certificate.
I can decode the elements of the certificate with der_decode_sequence but I can't find a way to get the data I need for verifying the signature.

Do I miss something or is this just not supported by the DER decoder in libtomcrypt.

Best regards
  Lars

### Steps to Reproduce
N/A

### Version
master/b96e96cf8

### Additional Information

N/A

**Comment by sjaeckel** [comment]
On master that's currently not possible.

On develop you can use the flexi decoder which now stores the original data before decoding in `ltc_asn1_list->data`.

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
