### ISSUE TITLE
Cannot compile with msvc2012 x86

### ISSUE THREAD

**Issue by stef-pellegrino** [libtom/libtomcrypt#637]
Hi,

Get this error under windows11, with old msvc 2012 x86 :

nmake -f makefile.mscv
...
**src/prngs/rng_get_bytes.c(117) : error C2143: syntax error : missing ';' before 'type'**
**rc/prngs/rng_get_bytes.c(118) : error C2065: 'hProv' : undeclared identifier
src/prngs/rng_get_bytes.c(126) : error C2065: 'hProv' : undeclared identifier
src/prngs/rng_get_bytes.c(129) : error C2065: 'hProv' : undeclared identifier**

An idea ?
Thanks

**Comment by sjaeckel** [comment]
Oh wow MSVC.

You can apply the `src/prngs/rng_get_bytes.c` part of b182b973ffc4ba629ac087ce53eaa5b4bcdf0dd9, this apparently fixes the error.
