### ISSUE TITLE
ltc_math_descriptor redefinition error when attempting to compile using LTM as math provider.

### ISSUE THREAD

**Issue by Allevon412** [libtom/libtomcrypt#642]
### Prerequisites

* [x] Checked the developer manual
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=repo%3Alibtom%2Flibtomcrypt
* [x] Checked that your issue isn't due to the fact that you're using asymmetric cryptography and you forgot linking in and/or setting an MPI provider (usually this causes either random crashes or runtime errors like `LTC_ARGCHK 'ltc_mp.name != NULL' failure ...`). c.f. Ch. "Math Descriptors" of the developer manual.
* [x] Checked that your issue isn't related to TomsFastMath's limitation that PK operations can by default only be done with max. 2048bit keys

### Description

[Description of the issue]

My issue is in attempting to compile the libtomcrypt library using visual studio 2022. I hit the following error when I attempt to using the tommath.lib library as the math provider. I have the following math provider defined in tomcrypt_custom.h

/* ---> math provider? <--- */
#ifndef LTC_NO_MATH

/* LibTomMath */
 #define LTM_DESC 

/* TomsFastMath */
/* #define TFM_DESC */

/* GNU Multiple Precision Arithmetic Library */
/* #define GMP_DESC */

#endif /* LTC_NO_MATH */

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2371	'ltc_math_descriptor': redefinition; different basic types	libtomcrypt	D:\OffsecTools\libtomcrypt\src\headers\tomcrypt_math.h	501		

### Version
#define SCRYPT  "1.18.2-develop"

You can get this information from the define `SCRYPT` in `src/include/tomcrypt.h` or your local git repository by running `git describe --always --tags --dirty`. 
Also, please include the compiler, the compiler version, the architecture and (if applicable) the MPI provider, the OS and what version of the OS you're experiencing the issue.
Windows 10 x64 bit Visual Studio compiler 2022.
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sjaeckel** [comment]
Can you please give more details on how to reproduce the error?

We're successfully building ltc+ltm with MSVC in our AppVeyor CI jobs, so I suspect a configuration issue, resp. an issue with how you build the libraries.

**Comment by Allevon412** [comment]
Here are some more screenshots of my current configuration. What other information do you think you would need?

![image](https://github.com/libtom/libtomcrypt/assets/41178870/acfaf37d-003d-46ff-aef2-7130d175d888)
![image](https://github.com/libtom/libtomcrypt/assets/41178870/61bd4912-005e-4b35-a79a-8dd5e9bbcb46)
![image](https://github.com/libtom/libtomcrypt/assets/41178870/ac2a0d59-9632-4fbb-b4cc-f6fe5d43ee74)

**Comment by Allevon412** [comment]
any word on this? all i tried to do was build using default settings in MSVS 2022 release x64 bit architecture.

**Comment by Allevon412** [comment]
Nvm I got it to build by adding #pragma once to the tomcrypt_custom.h file to negate the redefinition. I am assuming the header being included in multiple files caused a weird compiler error where it was being defined everywhere.

**Comment by Allevon412** [comment]
Just kidding. the pragma comment allows it to compile. However, now when I try to use the library object in my code and link it correctly I get he following errors all related to the ltm_desc.obj file. Which is the file where the function definitions for the ltm_math_descriptor exist.

![image](https://github.com/libtom/libtomcrypt/assets/41178870/f6ce40e3-54e1-4567-b29e-5586398894d8)
