### ISSUE TITLE
RSA check is abnormal. Procedure

### ISSUE THREAD

**Issue by Yolelg** [libtom/libtomcrypt#648]
version：1.18.2

**This is my python signature function：**

def sign_message_with_pkcs_sha1(message, private_key_der):
    if isinstance(message, str):
        message_bytes = message.encode('utf-8')  # Convert string to bytes if it's a string
    elif isinstance(message, bytes):
        message_bytes = message  # Use bytes directly if it's already bytes
    else:
        raise TypeError("Plaintext must be either a string or bytes")

    # Load DER format private key
    private_key = serialization.load_der_private_key(private_key_der, password=None, backend=default_backend())

    # Hash the message using SHA-1
    digest = hashes.Hash(hashes.SHA1(), backend=default_backend())
    digest.update(message_bytes)
    hashed_message = digest.finalize()

    # Sign the hashed message using PKCS#1 v1.5 padding
    signature = private_key.sign(
        message_bytes,
        padding.PKCS1v15(),  # Use PKCS#1 v1.5 padding
        hashes.SHA1()
    )

    return signature

**This is my C signature function**

  data = b'1'
  rsa_sign = sign_message_with_pss_sha1(data, private_key);
  print(f"len is {len(rsa_sign)}")
  print(binascii.hexlify(rsa_sign).decode('utf-8'))

  const unsigned char sha1_hash[] = { 0x31};
  printf("hash_descriptor[0].name is %s\r\n", hash_descriptor[0].name); //sha1
  if (rsa_sign_hash_ex(sha1_hash, 1, signature, &signature_len, LTC_PKCS_1_V1_5, NULL, 0, 0, 0, &key_private) != CRYPT_OK) {
      printf("Error signing data\n");
      return 1;
  }

I use the same signature and key why the encrypted signature is inconsistent, and the signature verification has always failed

**Comment by sjaeckel** [comment]
Please give a full working example of the C code and we can maybe help.

The only thing I can say is, that we are testing against the official set of testvectors and there's no problem known so far. C.f. `tests/pkcs_1_*_test.c` resp. the files in `notes/rsa-testvectors/`.

**Comment by Yolelg** [comment]
[rsa.zip](https://github.com/user-attachments/files/16606684/rsa.zip)

The C method verifies the signature without problem

Signing with python (server side) and then checking with c (client side) fails;


I printed rsa signatures in both languages and found that they were different


Note:
The keys and parameters of the two languages are the same, but the output signatures are different. In this case, the signature check will definitely fail.

Please help me look at this problem

I added the code to the attachment

**Comment by sjaeckel** [comment]
You could inspect the decrypted data here

https://github.com/libtom/libtomcrypt/blob/2302a3a89752b317d59e9cdb67d2d4eb9b53be8e/src/pk/rsa/rsa_verify_hash.c#L75-L78

After the call to `rsa_me()` the `tmpbuf` should contain your PKCS#1 v1.5 padded hash and maybe you can spot the difference.

Wild guess: maybe you want `LTC_PKCS_1_V1_5` instead of `LTC_PKCS_1_V1_5_NA1`?

> the output signatures are different.

That's one of the key aspects of PKCS#1 v1.5, it contains random data in the padding, so each signature of the same data will be different.

If you don't find the solution, feel free to provide an example signature of the python tool, so I can have a look.

**Comment by Yolelg** [comment]
Here's the output, but I don't understand it
```
 if ((err = ltc_mp.rsa_me(sig, siglen, tmpbuf, &x, PK_PUBLIC, key)) != CRYPT_OK) { 
    XFREE(tmpbuf); 
    return err; 
 } 
```

```
output tmpbuf hex for c：
0001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00300e300906052b0e03021a0500040131
```

I changed the c code to LTC_PKCS_1_V1_5, I tried to run it multiple times and the output signature was the same every time

`output sign hex for c：2367563df96068934f42783229581e106b35dfef1c32cdcf2c15a3fa2c8077c5746d9956d3f6b175a484bbb82ad99009f783eca586758ff226e15df5f5074af695abb6528e47026a8d141a5eb556765cad3c55593e3343e5b0c7f87a5a157744f9af1924d63186e7a241cb568865b54627bbbf9e2c05a43f0af9f118e41454d9`

### **c code:**

```
#include "tomcrypt.h"
#include "tomcrypt_custom.h"


#include <stdio.h>
#include <string.h>
#define LTM_DESC

// der ak sk with base64 same sa python
unsigned char private_rsa_base64[] = "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJKSRvUqzD+c2n/dy+5uYrs9tK12NUuSigLtRrfEHngmKAO4Nt+QGCw2o1Q8Wf91K2h0dZjmC1kPb+xtMinLk5oDKotbXCd28ID5a/lkhmsCDdZSebgbeVchCblGFmgvoeoZL+UABOW9sR6R1Gczq9CuWqAKV6/xzJ8/aOxH2RFVAgMBAAECgYAIcVKTBq8TLvbLDLyVdFhNjsVchIWXX86BUqeTKEHVC+WcKT1H7WXnDhKkZIGOnHIupx6q+v1GWQRKaxPLooVS8FAk0LI25mp5dBRkIVz2AoU3f6Wohaj0NZ+pWFxAv1V2SLHSBoB5vCtwnIj4ZHQWo8FUYWVRO6nqsGJRQGh5lQJBANeYp3IjX3kzTxiTRNvfyE2agAeZtRAGZAjSzU1mzjf3lTNuaDxp2vcLeQM7gu0CXuO5EwP9KXXVOgtdsvVs1bsCQQCuCh3nQM+LLMI3y5pOZFr+A5PPPQrBBi8SQW9lA1hZ2L4ilBIR5cH3mOmTpNT9L6SpvjosjcAgvuHCHWxE8jwvAkA8WJZF9HC81AfHsTEM+k5uqlg7yGJN4fwOHDMq/yOptrskcjrq7hZEIAn3RakX/hnhU+RmsW3xdYWRuOBmodgRAkEAoEqhEAQZIs2uc0UKcXjsdVdGI3DNHspbQC0UM6zJCrcdJyvJGMLLywcC2gDOSgI/XjbdzXsgoQgtVWNT/Iw98QJAMH8T7remwfPOZnOuFSotKM33/6S856AirXFT/y8WQaSrayHnKLyfjNLOTG/B7mObyvo6QqvAKfogh9RaqfbyLA==";
unsigned char public_rsa_base64[] = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSkkb1Ksw/nNp/3cvubmK7PbStdjVLkooC7Ua3xB54JigDuDbfkBgsNqNUPFn/dStodHWY5gtZD2/sbTIpy5OaAyqLW1wndvCA+Wv5ZIZrAg3WUnm4G3lXIQm5RhZoL6HqGS/lAATlvbEekdRnM6vQrlqgClev8cyfP2jsR9kRVQIDAQAB";

static prng_state yarrow_prng;

int main() {

    /// init
	ltc_mp = ltm_desc;

    /* register yarrow */
    if (register_prng(&yarrow_desc) == -1) {
        printf("Error registering Yarrow\n");
        return -1;
    }

    if (register_hash(&sha1_desc) == -1) {
        printf("Error register_hash\n");
        return 1;
    }

    int prng_idx = find_prng("yarrow");
    int hash_idx = find_hash("sha1");

    if (prng_idx == -1) {
        printf("Error prng_idx\n");
        return 1;
    }
    
    if (hash_idx == -1) {
        printf("Error hash_idx\n");
        return 1;
    }

    printf("--------------%d \n", __LINE__);

    /// rsa ak sk
    rsa_key key_public;
    rsa_key key_private;

    // get ak
    int pub_size = sizeof(public_rsa_base64) * 4;
    unsigned char * pub_buf = (unsigned char *)malloc(pub_size);
    memset(pub_buf, 0, pub_size);
    base64_decode(public_rsa_base64, strlen(public_rsa_base64), pub_buf, &pub_size);
    printf("ak size = %d \n", pub_size);
    rsa_import(pub_buf, pub_size, &key_public);
    printf("ak type:%d \n", key_public.type);
    free(pub_buf);

    //get sk
    int pri_size = sizeof(public_rsa_base64) *16;
    unsigned char * pri_buf = (unsigned char *)malloc(pri_size);
    memset(pri_buf, 0, pri_size);
    base64_decode(private_rsa_base64, strlen(private_rsa_base64), pri_buf, &pri_size);
    rsa_import_pkcs8(pri_buf, pri_size, NULL, 0, &key_private);
    printf("sk size = %d \n", pri_size);
    printf("sk type:%d \n", key_private.type);
    free(pri_buf);

    // rsa sign  // Here I did the same thing in python and the signatures I printed were inconsistent 
    int state = -1;
    unsigned char signature[256] = {0}; 
    unsigned long signature_len = sizeof(signature);
    const unsigned char data = '1';
    printf("hash_descriptor[0].name is %s\r\n", hash_descriptor[hash_idx].name); // is sha1

    if (rsa_sign_hash_ex(&data, sizeof(data), signature, &signature_len, LTC_PKCS_1_V1_5, &yarrow_prng, prng_idx, hash_idx, 0, &key_private) != CRYPT_OK) {
        printf("Error signing data\n");
        return 1;
    }

    //#prinf rsa sign // The output is different from python code
    printf("Signature (hex) len(%d): ", signature_len);
    for (unsigned long i = 0; i < signature_len; ++i) {
        printf("%02x", signature[i]);
    }
    printf("\n");

    // rsa verify
    int verify_result = rsa_verify_hash_ex(signature, signature_len, &data, sizeof(data), LTC_PKCS_1_V1_5, hash_idx, 0, &state, &key_public);
    if (verify_result == CRYPT_OK && state == 1) {
        printf("Signature verified successfully\n");
    } else {
        printf("Signature verification failed\n");
    }

    return 0;
}
```

### **for python**
`output sign hex for python：4d881b5c9f9c9f6de1a935f578016b5b7799dbe4a0c6ea306a9707e9a31069ee9775a54e1db1a3c0c5ac32e0ff4fdf9cc73dc4358507b05311b4f3e16a44b473d63ebacfe180503d08c486bcf8d500f600a3cb3d0148e52fd238aacb0efffd7746d75b4aa8b9306be7b73398be368667ad66f67824ddd2746d5febe3c7e9403b`

### code：

```
import base64 
import binascii

from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.backends import default_backend
RSA_PRIVATE_KEY = "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJKSRvUqzD+c2n/dy+5uYrs9tK12NUuSigLtRrfEHngmKAO4Nt+QGCw2o1Q8Wf91K2h0dZjmC1kPb+xtMinLk5oDKotbXCd28ID5a/lkhmsCDdZSebgbeVchCblGFmgvoeoZL+UABOW9sR6R1Gczq9CuWqAKV6/xzJ8/aOxH2RFVAgMBAAECgYAIcVKTBq8TLvbLDLyVdFhNjsVchIWXX86BUqeTKEHVC+WcKT1H7WXnDhKkZIGOnHIupx6q+v1GWQRKaxPLooVS8FAk0LI25mp5dBRkIVz2AoU3f6Wohaj0NZ+pWFxAv1V2SLHSBoB5vCtwnIj4ZHQWo8FUYWVRO6nqsGJRQGh5lQJBANeYp3IjX3kzTxiTRNvfyE2agAeZtRAGZAjSzU1mzjf3lTNuaDxp2vcLeQM7gu0CXuO5EwP9KXXVOgtdsvVs1bsCQQCuCh3nQM+LLMI3y5pOZFr+A5PPPQrBBi8SQW9lA1hZ2L4ilBIR5cH3mOmTpNT9L6SpvjosjcAgvuHCHWxE8jwvAkA8WJZF9HC81AfHsTEM+k5uqlg7yGJN4fwOHDMq/yOptrskcjrq7hZEIAn3RakX/hnhU+RmsW3xdYWRuOBmodgRAkEAoEqhEAQZIs2uc0UKcXjsdVdGI3DNHspbQC0UM6zJCrcdJyvJGMLLywcC2gDOSgI/XjbdzXsgoQgtVWNT/Iw98QJAMH8T7remwfPOZnOuFSotKM33/6S856AirXFT/y8WQaSrayHnKLyfjNLOTG/B7mObyvo6QqvAKfogh9RaqfbyLA==";
RSA_PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSkkb1Ksw/nNp/3cvubmK7PbStdjVLkooC7Ua3xB54JigDuDbfkBgsNqNUPFn/dStodHWY5gtZD2/sbTIpy5OaAyqLW1wndvCA+Wv5ZIZrAg3WUnm4G3lXIQm5RhZoL6HqGS/lAATlvbEekdRnM6vQrlqgClev8cyfP2jsR9kRVQIDAQAB";

def verify_message_with_pkcs1v15_sha1(message, signature, public_key_der):
    if isinstance(message, str):
        message_bytes = message.encode('utf-8')
    elif isinstance(message, bytes):
        message_bytes = message
    else:
        raise TypeError("Plaintext must be either a string or bytes")

    public_key = serialization.load_der_public_key(public_key_der, backend=default_backend())

    try:
        public_key.verify(
            signature,
            message_bytes,
            padding.PKCS1v15(),
            hashes.SHA1()
        )
        print("Signature is valid.")
        return True
    except Exception as e:
        print(f"Signature verification failed: {e}")
        return False

def sign_message_with_pkcs1v15_sha1(message, private_key_der):
    if isinstance(message, str):
        message_bytes = message.encode('utf-8')
    elif isinstance(message, bytes):
        message_bytes = message
    else:
        raise TypeError("Plaintext must be either a string or bytes")

    private_key = serialization.load_der_private_key(private_key_der, password=None, backend=default_backend())

    signature = private_key.sign(
        message_bytes,
        padding.PKCS1v15(),
        hashes.SHA1()
    )

    return signature

def main():

    private_key = base64.b64decode(RSA_PRIVATE_KEY)

    data = b'1'
    rsa_sign = sign_message_with_pkcs1v15_sha1(data, private_key);
    # prinf rsa sign // The output is different from c code
    print(f"len is {len(rsa_sign)}")
    print(binascii.hexlify(rsa_sign).decode('utf-8'))

    public_key = base64.b64decode(RSA_PUBLIC_KEY)
    ret = verify_message_with_pkcs1v15_sha1(data, rsa_sign, public_key);
    print(f"ret is {ret}")

if __name__ == "__main__":
    main()
```

Note：
I tested it in java, and its output is the same as python's

**Comment by Yolelg** [comment]
for c code , I use libtommath-1.3.0, libtomcrypt-1.18.2

**Comment by levitte** [comment]
You're misusing `rsa_sign_hash_ex()`.  It's not hashing the data for you, so the data to be signed must be pre-hashed, i.e. you have to hash it on your own.  The manual does say this:

https://github.com/libtom/libtomcrypt/blob/2302a3a89752b317d59e9cdb67d2d4eb9b53be8e/doc/crypt.tex#L4599

("the message digest pointed to by *in*" really means what it says)

**Comment by levitte** [comment]
The only reason that `rsa_sign_hash_ex` still needs to know that you use `sha1` is that the hash function's OBJECT IDENTIFIER is a part of the PKCS#1v1.5 encoding.

You know the string you showed earlier?  I.e. this:

```
0001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00300e300906052b0e03021a0500040131
```

This part is DER encoded data: 300e300906052b0e03021a0500040131
It's easy to decode with OpenSSL:

``` console
$ echo 300e300906052b0e03021a0500040131 | xxd -r -p | openssl asn1parse -inform der -i
    0:d=0  hl=2 l=  14 cons: SEQUENCE          
    2:d=1  hl=2 l=   9 cons:  SEQUENCE          
    4:d=2  hl=2 l=   5 prim:   OBJECT            :sha1
   11:d=2  hl=2 l=   0 prim:   NULL              
   13:d=1  hl=2 l=   1 prim:  OCTET STRING      :1
```

'2b0e03021a' is the OBJECT IDENTIFIER itself, and translates to this (which OpenSSL knows is 'sha1'): 1.3.14.3.2.26

**Comment by Yolelg** [comment]
Is there any sample code for this? Which functions should I use

**Comment by levitte** [comment]
Two choices:

1.  You could use functions in `hash_descriptor[hash_idx]`, taking cues from this example in the documentation:

    https://github.com/libtom/libtomcrypt/blob/2302a3a89752b317d59e9cdb67d2d4eb9b53be8e/doc/crypt.tex#L2672-L2676

2.  You could using `sha1_init()`, `sha1_process()` and `sha1_done()` directly, taking cues from this example in the documentation:

    https://github.com/libtom/libtomcrypt/blob/2302a3a89752b317d59e9cdb67d2d4eb9b53be8e/doc/crypt.tex#L2589-L2596

**Comment by Yolelg** [comment]
Thank you very much, I succeeded, I think I should read the manual more carefully, finally thank you!
