### ISSUE TITLE
Is AES-GCM supported？

### ISSUE THREAD

**Issue by Yolelg** [libtom/libtomcrypt#649]
I didn't find any AES-GCM related functions or interfaces

**Comment by levitte** [comment]
In libtomcrypt, cipher modes are implemented as wrapper functions to apply to the base ciphers.  GCM is described in the manual, in Chapter 5 - Authenticated Encryption, section GCM Mode.

**Comment by Yolelg** [comment]
Okay, thanks. I'll go study
