### ISSUE TITLE
Importing Binary Private Key To RSA_KEY

### ISSUE THREAD

**Issue by EclipseStudios** [libtom/libtomcrypt#71]
I currently have all the parameters to an RSA key, but find it impossible to import them to the rsa_key parameter. For instance, in C# I simply do this:

            RSACryptoServiceProvider Key = new RSACryptoServiceProvider();
            RSAParameters parameters = new RSAParameters();
            reader.Seek(0x28C);
            parameters.Exponent = reader.ReadBytes(0x4);
            reader.Seek(0x8, SeekOrigin.Current);
            parameters.Modulus = Conversions.FlipBytesBy8(reader.ReadBytes(0x80));
            parameters.P = Conversions.FlipBytesBy8(reader.ReadBytes(0x40));
            parameters.Q = Conversions.FlipBytesBy8(reader.ReadBytes(0x40));
            parameters.DP = Conversions.FlipBytesBy8(reader.ReadBytes(0x40));
            parameters.DQ = Conversions.FlipBytesBy8(reader.ReadBytes(0x40));
            parameters.InverseQ = Conversions.FlipBytesBy8(reader.ReadBytes(0x40));
            parameters.D = new byte[0x80];
            Key.ImportParameters(parameters);

But in C, it's not possible to just set the void* parameters, since I'm assuming they use some sort of big integer type that I cannot find. I would like to some how change the data to whatever type of format rsa_import uses.

**Comment by sjaeckel** [comment]
Well if you implemented your own math provider you can set the void* parameters to whatever your provider likes.

**Comment by EclipseStudios** [comment]
I'm using LibTomMath. I'm not sure how I'd set up their big integers to use from mere bytes (unsigned char *).

**Comment by sjaeckel** [comment]
Hint: I'd have a look at `mp_read_unsigned_bin()`
