### ISSUE TITLE
mem_neq

### ISSUE THREAD

**Issue by sebastianv89** [libtom/libtomcrypt#74]
[mem_neq](https://github.com/libtom/libtomcrypt/blob/develop/src/misc/mem_neq.c) is a constant time comparison function, but it leaks information on the secret data that is being compared in the value that is returned.

**Comment by tomatelliptic** [comment]
Just do a folding of the ret code then ...

```
ret |= ret >> 4;
ret |= ret >> 2;
ret |= ret >> 1;
ret &= 1;
```

Magic.

**Comment by tomstdenis** [comment]
I should have posted that with my private github account :-)

**Comment by sebastianv89** [comment]
Maybe faster:
return !!ret;

**Comment by tomstdenis** [comment]
"!!ret" could in theory have branches in it.  If you want a fixed time implementation the folding is the way to go.
