### ISSUE TITLE
The website http://www.libtom.net/ seems to be down

### ISSUE THREAD

**Issue by BrightEtoile** [libtom/libtomcrypt#84]
The website listed in the description http://www.libtom.net/ seems to be down. I got ERROR 504 when I tried to visit it.
And I found other website https://libtom.github.io/, which seems to be an official website. Is it build to replace http://www.libtom.net/?
If yes, I suggest updating the description.
Thanks.

**Comment by sjaeckel** [comment]
Cool (well not really cool, but that was supposed to happen), thanks for reporting this.
Changed to www.libtom.org
