### ISSUE TITLE
Feature request: Serpent

### ISSUE THREAD

**Issue by kelvinjm** [libtom/libtomcrypt#86]
This library is really brilliant. I have made some speed tests against other common libraries and this one is really perfect. It would be really nice to implement the Serpent algorithm. After all, it's considered as maybe the safest one.

**Comment by sjaeckel** [comment]
This has already been asked multiple times and TBH I share the opinion of @tomstdenis 

https://groups.google.com/d/msg/libtom/M-ygMdHcgXU/ltvsVT5u6fcJ
https://groups.google.com/d/msg/libtom/ir3RhhjDvMc/QGH9fcymdcYJ

Therefor I close this issue.

If you think that you really need Serpent in ltc, feel free to provide a public domain implementation and integrate it. Then open a new PR.
