### ISSUE TITLE
Attached: CMake build file

### ISSUE THREAD

**Issue by ZahlGraf** [libtom/libtomcrypt#87]
Hi

first of all I want to say: Thanks for that cool library. It is also very well documented :)

Since I'm a big fan of CMake, that makes building for different systems and with different compilers very easy, I created a CMakeLists.txt file.

Maybe someone else find this useful, that's why I just want to attach it to this text:
[CMakeLists.txt](https://github.com/libtom/libtomcrypt/files/76093/CMakeLists.txt)

I have tested it with MSVC2015 (Windows 64bit), GCC 4.9 (Linux64) and Android NDK r10e. It builds libtomcrypt as static library. On windows it shows some linker warnings at linking stage, but I think this is not an issue (object files without external symbols). 

There are a lot of compilers and systems out there, where this CMakeLists.txt has not been tested with, but I think it is at least a starting point for other users, that want to use libtomcrypt together with CMake.

Have a lot of fun with it :)
BR

**Comment by rofl0r** [comment]
-1

**Comment by sjaeckel** [comment]
kthx
