### ISSUE TITLE
camellia.c const is meaningless on cast type

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#92]
I have experienced the following compiler warning:
```
"src/ltc/ciphers/camellia.c", line 193: warning #2191-D: type qualifier is
          meaningless on cast type
     U = D ^ ROR(U, (const int)8);
                     ^
```

Why not just use: `U = D ^ ROR(U, 8);` ?

**Comment by sjaeckel** [comment]
well we could use RORc at that place as it's a rotate by a constant amount of bits, but the cast doesn't make sense.
can you try if `RORc(U, 8)` works for you? I just tested on x84_64 and it's fine

**Comment by sjaeckel** [comment]
that just made me think of 62878de0c5dbb9f89474590d953bbdb339bd2f76 when I saw the PPC `ROXc()` functions

**Comment by karel-m** [comment]
changing to `RORc(U, 8)` works
