### ISSUE TITLE
Possible bug in ecc_sign_hash

### ISSUE THREAD

**Issue by rkreicbergs** [libtom/libtomcrypt#94]
ECDSA algorithm fails to crop input hash to key length in ecc_sign_hash_raw()

The docs says:
With ECC if you try to sign a hash that is bigger than your ECC key
you can run into problems. The math will still work, and in effect the
signature will still work. With ECC keys the strength of the signature
is limited by the size of the hash, or the size of they key, whichever is
smaller. For example, if you sign with SHA256 and an ECC-192 key,
you in effect have 96–bits of security.
The library will not warn you if you make this mistake, so it is
important to check yourself before using the signatures.

The "math" will not really work. Compare the signature when the input is cropped (as defined in the specs) - the r is the same (assuming k is the same), but s values will not be congruent modulo n. So the "math" will only work if the validation is also done using TomCrypt.

Thus the input length should be validated or the input should be cropped to the key size.

**Comment by karel-m** [comment]
I only want to note that this part of ECC was significantly changed in my proposal #65 (ECC enhancements)

The relevant section starts here https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ecc_sign_hash.c#L70

I am not saying that my code is not affected by the above described issue as I have not investigated more details. Some failing demo/example or failing test data would be helpful.

**Comment by rkreicbergs** [comment]
Read through your code - looks good as only _pbits_ are read from input as in the specs.
